### ISSUE TITLE
Ekstra Mars 2015: Functional Programming i grensesnittet

### ISSUE THREAD

**Issue by mikaelbr** [BartJS/meetups#11]
Kjøre en introduksjon til React (og se på Omniscient.js), og bruk av Immutabel data (via Immutabel.js).
En helaften med en mer funksjonell tilnærming for UI.

@torgeir Mulighet til å være med rundt 10. november -> 14. november?

**Comment by mikaelbr** [comment]
Flyttet til april. Passer, @torgeir ?

**Comment by torgeir** [comment]
Ja, det ordner vi.

**Comment by mikaelbr** [comment]
@torgeir Tror kanskje det er på tide å retire denne?

**Comment by torgeir** [comment]
Hehe. Det drøyde litt dette. Tror forsatt én eller annen variant av det kan være interessant for mange, men har ingen ting i ermet. Kan lage et nytt issue evnt. hvis det er interesse?

**Comment by mikaelbr** [comment]
Ja, jeg er enig i at en derivert utgaver har livets rett. Vi kan hvile litt på den og så skal jeg prøve å ta tak igjen om litt 😄

**Comment by torgeir** [comment]
Jep, samme her! Da kan denne lukkes.

**Comment by mikaelbr** [comment]
Og sannsynligvis da fjerne den på Meetup.com? :P
