### ISSUE TITLE
Mars 2015

### ISSUE THREAD

**Issue by lroal** [BartJS/meetups#14]
Jeg har vært i kontakt med Mikael og meldt meg til å holde en presentasjon. Det blir enten om [rdb](https://npmjs.org/package/rdb) , en ORM jeg har skrevet selv, eller om [tdd og mock rammeverket a](https://npmjs.org/package/a) som jeg og en kollega vedlikeholder. Begge bibliotekene brukes i Timpex hvor jeg jobber.

Da det skjer litt mye på hjemmebane har jeg ikke anledning før i mars.

Jeg kan antakelig få arbeidsgiver til å sponse møtet. Vi kan bruke et møterom i Teknobyen.

**Comment by mikaelbr** [comment]
Veldig bra, @lroal ! Det har vært veldig mye som har skjedd både for meg og @mollerse i det siste, så vi trenger at andre tar slikt initativ som dette!

**Comment by bjornamr** [comment]
Høres kult ut! Håper dere oppdaterer nærmer på satt dato og sted.  Kan gjerne bidra med erfaringer rundt bruk av native api som kompass og vibrasjon i javascript på mobil om det er noe interesse for det en gang. Driver å tester ut dette i bacheloroppgaven jeg skriver.

**Comment by lroal** [comment]
Hei, @bjornamr . Det høres jo interessant ut. Er det via phonegap ?

**Comment by bjornamr** [comment]
@lroal , det er uten noe wrapping faktisk. Vi skal prøve å kjøre det som ren nettisde. Det blir altså ingen app, men en nettside med disse funksjonene. Det blir bare ren javascript og HTML.

Men jeg har hatt to prosjekter i  Cordova ( Phonegap) også.

**Comment by lroal** [comment]
Skal vi sette en dato ? Tirsdager passer bra for meg. Feks. 24 mars

**Comment by mikaelbr** [comment]
Ja, sett en dato, så kan jeg opprette en Meetup.com på det! 24. mars passer for min del også forsåvidt.

**Comment by lroal** [comment]
Har @bjornamr anleding 24. mars ?

**Comment by bjornamr** [comment]
@lroal , tror det passer for meg etter 16 den datoen.

**Comment by tellnes** [comment]
Tirsdag passer ikke for meg etter halv syv, men ikke la dere stoppe av det. Kun en -1 på den dagen fra meg.

**Comment by mikaelbr** [comment]
Hva tror dere @bjornamr og @lroal ? Dersom dere kommer med en tekst, sted og dato for meetupen skal jeg lage en Meetup på meetup.com om det, så får vi vist at det skal skje noe.

**Comment by bjornamr** [comment]
@mikaelbr, jeg er gira jeg. Jeg har ikke noe sted som vi kan sitte. Det må eventuelt ha blitt på skolen på HiST om det er krise. Jeg har mulighet 24. etter klokken 16. 

Jeg vil gjerne høre om rdb som @lroal  pratet om lengre opp. Hadde også vært kult enten denne gangen eller en annen gang om det er interesse å teste ut flere native funksjoner som er kommet til JavaScript. Målet kunne jo vært å lage noe som lignet en app på en telefon men ved bruk av javascript da og uten Cordova.

**Comment by mikaelbr** [comment]
@bjornamr Tanken vil da være at @lroal snakker om rdb og du gir en intro til native mobile APIs. Så kan du gjennomføre en workshop på et senere tidspunkt om du vil det!

@torgeir og jeg har også planlagt en workshop innen kort tid, men er litt opptatt om dagen med å forberede til en annen konferanse.

**Comment by lroal** [comment]
Er denne teksten grei nok, @mikaelbr ?
__rdb__ (30-40 min)
Rdb is a new object relational mapper (ORM) for mySql and postgreSql. It has transactions, persistence ignorance and is based on  promises. We explore different kinds of mappings, query filters and persistence. We also give a brief background to the reason it was made, inspirational factors, development methodology, patterns and anti patterns. Rdb was initially based on a closed source in csharp at Timpex, but we decided to purify it and publish as open source in nodejs. It is used in commercial products today. 

Presentation will be held in Norwegian, but all slides and examples are in English.

**Comment by lroal** [comment]
Skal vi si klokken 18 i Abels gate 5 (Teknobyen) ?
Timpex sponsor lokale og servering. Er det vanlig å ha mat før eller etter presentasjonene ?
Jeg skal sjekke kapasiteten på møterommene i morra, men kan antakelig booke om i forhold til antallet. Eventuelt ta det i nabobygget hvis vi blir mange.

**Comment by bjornamr** [comment]
@milaelbr, kan holde en liten intro om native api og bruksområder. 

@lroal 18 er greit for meg

**Comment by mikaelbr** [comment]
@lroal 
> Timpex sponsor lokale og servering. Er det vanlig å ha mat før eller etter presentasjonene ?

Det er ikke uvanlig. Det er opp til de som arrangerer om de har sponsor. Dersom det er klokken 18:00 kan det være greit at det er mat for mange vil dra rett fra jobb / rekker ikke stikke innom hjemme.

> Jeg skal sjekke kapasiteten på møterommene i morra, men kan antakelig booke om i forhold til antallet. Eventuelt ta det i nabobygget hvis vi blir mange.

Det er litt ymse hva som kommer. Vi har vært alt fra 50 til 14.

> Er denne teksten grei nok, @mikaelbr ?

Ja, ser bra ut!

--- 

@bjornamr Flott. Kan du skrive et lite abstract for det?

**Comment by bjornamr** [comment]
JavaScript has now more and more support for mobile devices. This could change how people interact and experience webpages.  I will give a brief talk about the compass api, vibration api and orientation api. I will give an example of how I am using the two first in my bachelor thesis im currently writing at HiST.

**Comment by mikaelbr** [comment]
Jepp. Tipp topp! Er 24. mars klokken 18:00 fastsatt, @lroal og @bjornamr, eller er det en dag som passer bedre?

Om alt det passer, oppretter jeg en meetup med følgende info:

----

**Sted**: Timpex, Abels gate 5 (Teknobyen)
**Tid**: 24. mars klokken 18:00
**Med servering sponset av Timpex**


**rdb (30-40 min) m/[Lars-Erik Roald](https://twitter.com/lroal)**
Rdb is a new object relational mapper (ORM) for mySql and postgreSql. It has transactions, persistence ignorance and is based on promises. We explore different kinds of mappings, query filters and persistence. We also give a brief background to the reason it was made, inspirational factors, development methodology, patterns and anti patterns. Rdb was initially based on a closed source in csharp at Timpex, but we decided to purify it and publish as open source in nodejs. It is used in commercial products today.

_Presentation will be held in Norwegian, but all slides and examples are in English._

**Native mobile APIs m/[Bjørnar Remmen](https://github.com/bjornamr)**
JavaScript has now more and more support for mobile devices. This could change how people interact and experience webpages. Bjørnar Remmen will give a brief talk about the compass api, vibration api and orientation api. He will give an example of how he is using the two first in his bachelor thesis he iscurrently writing at HiST.

**Comment by lroal** [comment]
Passer bra for meg.

**Comment by bjornamr** [comment]
Passer bra :) kan du legge ut en adresse / link til google maps her?

**Comment by lroal** [comment]
Her er kart, både [kart.finn.no](http://kart.finn.no/?lng=10.39540&lat=63.41587&zoom=17&mapType=normap&markers=10.39540,63.41587,r,ABELS+GATE+5) og [maps.google.com](https://www.google.no/maps/place/Abels+gate+5,+7030+Trondheim/@63.4158793,10.3954375,17z/data=!3m1!4b1!4m2!3m1!1s0x466d31eb4d3e0f41:0x40a6899ca0d99a43?hl=no)  
Liker godt finn jeg.

**Comment by mikaelbr** [comment]
Her er meetup-en. Ikke announcet enda, så kan dere se over at alt stemmer: http://www.meetup.com/BartJS/events/221122694/

**Comment by lroal** [comment]
Bare en ting, @bjornamr , hva legger du i compass API ?  Er det geolocation eller proximity ?  Jeg ser at feks at compassneedscalibration er en del av Device Orientation api.
(Jeg kan ikke noe om dette, bare lurte)

**Comment by lroal** [comment]
meetup ser bra ut.

**Comment by bjornamr** [comment]
@lroal  , det er device orientation jeg tenkte å gå gjennom. Men
Jeg er litt usikker på om jeg svarer rett på ditt spørsmål nå, så du må bare spørre på nytt om jeg misforsto.  Jeg tror ikke geolokasjon har noe med kompass å gjøre, men jeg skal ikke påstå noe om du har funnet noe annet.   
Det jeg har hørt og lest nå er at det digitale kompasset i en telefon baserer seg på to ting: den ene er noe som kalles det "the hall effect" og den andre går ut på det magnetiske feltet på jorda. 

Det magnetiske feltet består av flere retninger, men nord er da den sterkeste. Det kan komme forstyrrelser og det er også derfor man har et slikt event som man igjen da kan kalibrere telefonen med å bevege den i et åttetall. Disse forstyrrelsene kommer gjerne fra en PC eller andre ting som kan påvirke det målte feltet.


Hall effect sensor er altså navnet på sensoren  og den varierer slik: 
En Hall-effekt sensoren er en transduser som varierer sin utgangsspenning som reaksjon på et magnetisk felt. Transduser er noe som genrererer i dette tilfellet strøm fra magnetisk energi.
http://en.wikipedia.org/wiki/Hall_effect_sensor#/media/File:Hall_sensor_tach.gif

Jeg er usikker på om at det er slik at alle telefoner trenger kalibrering. 
http://physics.stackexchange.com/questions/17587/what-is-reason-for-electronic-compass-calibration

Den nederste og han i midten har noe ulikt utsagn. Men det kan virke som at om sensorene jobber i 3D så slipper man å kalibrere. Da går jeg ut ifra at compassneedcalibration aldri kjøres.

**Comment by lroal** [comment]
takker for info @bjornamr

**Comment by lroal** [comment]
@mikaelbr , jeg glemte å si at det er maks plass til ca 50 stykker, men det blir vel neppe noe problem.

**Comment by bjornamr** [comment]
@mikaelbr @lroal

Jeg hadde glemt hvilken dag det var på, var sikker på at det var i morra.. jeg hadde sett feil på kalenderen. Håper jeg kan komme neste gang for å fortelle litt.
Det var jo litt dumt at det ble sånn da, det beklager jeg.

**Comment by mikaelbr** [comment]
Vi kan endre datoen og forsåvidt? Jeg kan heller ikke dessverre da det oppsto en jobb-greie.

**Comment by bjornamr** [comment]
Det var vel i dag ser du ut som, ja. Men vi kan ta en annen dato,ja. Kan fortelle om det samme da.

forresten, hadde vært kult om vi kunne hatt quadcopter workshop en gang. Er det realistisk?

**Comment by lroal** [comment]
Avtalen var 24. Mars kl 18.
Se korrespondanse ovenfor.

**Comment by lroal** [comment]
Jeg har brukt tid på forberedelser og en familiekabal som skal gå opp.  Det er også sendt ut møteinnkallelse.

**Comment by bjornamr** [comment]
Åja,hah. Jeg har bare sett feil.
da er det null stress.

Noe dere vil jeg skal fokusere eller fortelle mer om?

**Comment by bjornamr** [comment]
@lroal bare jeg spm så feil. Går greit flr meg enda

**Comment by bjornamr** [comment]
@lroal , 

hvilke sammenhenger bruker man orm og hvilke lønner det seg ikke?  Hvilke minus er det?

**Comment by lroal** [comment]
@bjornamr
Jeg bruker det alltid når vi skal aksessere en relasjonsdatabase.
Pluss: 
slipper å håndkode sql statements. Det tar tid og inneholder ofte feil. Rader i databasen blir mappet direkte til javascript objekter. Enkelt å hente ut, lagre og slette data.

Minus: 
Å lære seg ORM apiet, kan være en bratt læringskurve. 
ORM biblioteker har alltid begrensinger i hva man gjøre i forhold til rå sql og legger ofte (, men ikke alltid, ) beskrantninger på hvordan man navngir tabeller, kolonner og relasjoner i den fysiske databasen.

**Comment by mikaelbr** [comment]
@lroal og @bjornamr : Hvordan gikk det i går? Hvor mange var det som møtte opp? Kunne gjerne tenkt meg å være der, men måtte dessverre dra på et jobbmøte.

**Comment by lroal** [comment]
Det var dårlig oppmøte. Inkludert foredragsholdere var det 8 stk. Fire fra timpex, @bjornamr og tre andre.
Sosialt sett var det jo hyggelig. Foredraget mitt ble kanskje litt langt og monotont, men gikk vel sånn passe.

**Comment by mikaelbr** [comment]
Ja, det hørtes ikke så mange ut. Kan være mange årsaker til det. Litt lite blasting og kanskje ikke godt nok jobb med å "selge inn" meetupen. Men det kan og være at mange ikke nødvendigvis bruker så mye server-side JS og/eller relasjonsdatabaser.

Flott at det ble gjort og vell gjennomført! Bidra gjerne flere ganger.

**Comment by lroal** [comment]
Jeg lukker issuen

**Comment by bjornamr** [comment]
Jeg synes det var lærerikt å høre på for min del.   Var også kjekt å kunne prøve å holde foredrag om bacheloren.
