### ISSUE TITLE
10. november meetup krasjer med MySQL om JSON meetup

### ISSUE THREAD

**Issue by tellnes** [BartJS/meetups#15]
Meetupen 10. november krasjer jo med MySQL meetypen om JSON. Kanskje man kunne hatt det på forskjellige dager?

http://www.meetup.com/Trondheim-MySQL-meetup-group/events/225942871/

**Comment by mikaelbr** [comment]
Ah, det er veldig uheldig. Det var et stort logistikk problem denne gangen, og tirsdag 10. november var eneste som passa for alle parter som skal være med å hoste det. I utgangspunktet skal jeg prøve å ikke legge opp meetups på dager der det kolliderer, men Trondheim begynner å få en del forskjellige meetups.
