### ISSUE TITLE
Feburar 2016

### ISSUE THREAD

**Issue by mikaelbr** [BartJS/meetups#18]
Foreslått foredrag:

1. Inge Solvoll - ClojureScript
2. TBA

Sted: TBA
Tid: TBA

Tanker: Kjøre et helt "transpile-to" meetup. F.eks ClojureScript & TypeScript? Eller Elm. Kanskje en med bevegelsen innen Babel og mulighetene det gir. F.eks er Sweet nå skrevet om og lagt på toppen av babel.

**Comment by mikaelbr** [comment]
@geirsagberg har sagt seg interessert i å snakke om TypeScript.

**Comment by mikaelbr** [comment]
Mulig denne kan flyttes til februar 2016. Og la januar være unidirectional/functional ui måneden. Med workshop og presentasjoner om f.eks redux og omniscient.

**Comment by ingesolvoll** [comment]
Hei!

Betyr det at jeg kan forberede meg på å gjøre noe i februar da?

**Comment by mikaelbr** [comment]
Ja, det stemmer! Vi kan komme frem til en dato det passer best for alle parter etterhvert.

**Comment by mikaelbr** [comment]
@ingesolvoll Er det noe tidspunkt som passer bra for deg i løpet av måneden? Helst sette av 2 dager. 1 dag til meetup og 1 dag til podcast! :cake:

**Comment by ingesolvoll** [comment]
Er bortreist 22-23 feb, ellers tror det meste skal gå greit!

Hvor mye tid blir det til presentasjon?

**Comment by mikaelbr** [comment]
Det er fritt frem hvor lenge du ønsker å snakke. Anbefaler rundt 30 minutt med fokusert innhold. Syns det har en tendens til å fungere best.

**Comment by geirsagberg** [comment]
Det meste passer for meg også :) Foredragstittel: "TypeScript - tøft eller toillat?"

**Comment by mikaelbr** [comment]
Herlig! Kan dere og skrive et lite abstract, så kan jeg legge det ut på Meetup.com? cc @ingesolvoll @geirsagberg

**Comment by ingesolvoll** [comment]
Tittel: ClojureScript - snakk med koden din

Abstract: 
Med forhatte paranteser og krav om Java som byggeverktøy er det mange som holder seg unna LISP-dialekten Clojure i nettleseren. Jeg skal vise hvorfor det kan være verdt å ta fatt på læringskurven. I LISP er kode data, og sammen med noen enkle men geniale utviklingsverktøy gir det oss interaktiv utvikling tatt til et helt nytt nivå.

Bio hvis du trenger:
Inge Solvoll jobber som systemutvikler i DNV GL i Trondheim, på JVM og web. Koser seg på the bleeding edge, glad i funksjoner uten side effects.

**Comment by mikaelbr** [comment]
Veldig bra! Jeg tror 17. februar blir den datoen for meetup og så håper jeg dere kan møte opp den 18. for podcast?

**Comment by ingesolvoll** [comment]
24-25 hadde vært enda bedre for meg, men 17-18 går helt fint det også.

**Comment by mikaelbr** [comment]
Flott. Er avhengig av 18. som podcast-dato for at det skal passe for alle parter.

**Comment by mikaelbr** [comment]
Hvordan ser det ut for din del, @geirsagberg

**Comment by mikaelbr** [comment]
Meetup ligger her: http://www.meetup.com/BartJS/events/228575204/

**Comment by ingesolvoll** [comment]
Jeg stiller med Windows PC med HDMI-utgang, kommer til å kjøre slides fra docs.google.com, og en del live koding. Regner med vi får WiFi? Får vi ok oppløsning på storskjermen? Det er spesielt viktig for meg å kunne vise kode og app side om side.

**Comment by mikaelbr** [comment]
Vi har ikke fått bestemt lokale enda, men skal sørge for å få testet ut prosjektor osv.

**Comment by geirsagberg** [comment]
17.-18. går fint:)

Tittel: TypeScript - tull eller tøft?

Abstract:
TypeScript er ikke bare Javascript med typer. Vi ser på hva dette transpilerte språket kan by på i 2016, med tanke på features, syntaks og verktøy. Er det lett å migrere et Javascript-prosjekt til TypeScript? Hva må man være obs på? Bør man gå for Babel eller TypeScript? Trenger man Webpack eller Browserify? Jeg deler erfaringer fra virkeligheten, med gode muligheter for live-koding.

Bio:
Geir Sagberg jobber som seniorutvikler i Bekk Trondheim. Han anser seg selv som full-stack utvikler og jobber til daglig med C# og Javascript, men har også tuklet en del med mobilutvikling (native og Xamarin). Han liker dataspill og indisk mat.

**Comment by mikaelbr** [comment]
Flott, folkens! Da har jeg annonsert meetupen. Foreløpig uten lokale, men er i dialog for å prøve å få det på Digs. Får svar ila morgendagen.

Da blir agendaen slik:

Onsdag 17. februar:
- 18:00 ClojureScript m/ @ingesolvoll (ca 30 min, ± etter behov)
- 18:30 TypeScript m/ @geirsagberg  (ca 30 min, ± etter behov)
- ±19:00 Muligens noe announcements/info
- >19:00 JSPils eller noe etterpå for diskusjon? Om det blir på Digs kan det være aktuelt å henge der etterpå.

Torsdag 18. februar
- 19:00? 20:00? Podcast sessjon på BEKKs lokaler på Ferjemannsveien 10. Kan fort ta rundt 2 timer. Ta gjerne med eget headset om dere har.

**Comment by mikaelbr** [comment]
@ingesolvoll @geirsagberg I morgen er det Meetup! Det ser ut som det er fullt hus til nå, men erfaringsvis blir det et subsett av de som kommer, men det ser uansett veldig bra ut! Dere kan gjerne komme ca 30 minutter før for å teste ut oppsett osv. Det skal være tilkobling HDMI eller VGA på en ny prosjektor. Er det noen andre spørsmål rundt dette?

På torsdag blir det da Podcast. Det blir i samme lokalet som Meetup-en, bare 3 etg. opp. Vi satser på å gjennomføre det 20:00 så oppmøte til da hadde vært supert. Skal prøve å få det til at alt er klart til da så det blir bare til å sette seg ned å snakke. Vi kjører en forholdsvis uformell tone. Det kan bli litt diskusjoner om hva ClojureScript og TypeScript er, hvordan de kan sammenlignes eller skilles. Men det kan og bli diskusjon rundt generell transpiling. Dette blir bra! Spørsmål rundt Podcasts?

**Comment by ingesolvoll** [comment]
Hei, @mikaelbr , ser ut som vi begge skal på Una først så da går vi vel bare sammen opp 17.30? Jeg har windows PC med HDMI, så det skal vel gå greit med setup.

20.00 på torsdag går fint! Vet ikke om jeg klarer å oppdrive et headset med mikrofon, jobber med saken.

**Comment by mikaelbr** [comment]
@ingesolvoll Ja, da går vi sammen! Det er ca 5 min gange bare, så ingen problem.

Du trenger ikke tenke på mikrofon. Vi har all utstyr for recording etc, men vi har ikke kjøpt inn egne headset for alle (ganske stor investering - og det viser seg at de fleste har egne headsets som de liker å bruke). Om du f.eks har et Bose qc25 eller lignende passer det perfekt. Om du ikke har noe lignende kan jeg sikkert skaffe deg et som du kan låne.

**Comment by mikaelbr** [comment]
@ingesolvoll Har skaffet headset. Trenger ikke tenke på det. Da er det bare til å møte opp. Trenger ingen ekstra ting foruten f.eks notater/data om det er noe du vet du vil snakke om eller nevne, eventuelt gjøre oppslag av noe slag.

**Comment by ingesolvoll** [comment]
Konge! Skal prøve å forberede meg litt da :)

**Comment by mikaelbr** [comment]
@ingesolvoll kan kontakte meg på 97981877 når du kommer til adressabygget (der vi var i går)

**Comment by mikaelbr** [comment]
@geirsagberg og @ingesolvoll: Podcast-episode er ute her: https://soundcloud.com/bartjs/episode-2-no-country-for-old-javascript

**Comment by mikaelbr** [comment]
Denne er gjennomført! Godt jobba alle sammen.
