### ISSUE TITLE
Angular 2.0

### ISSUE THREAD

**Issue by bendiksolheim** [BartJS/meetups#19]
Angular 2.0 er nå i beta, så det nærmer seg vel noe man kan kalle stabilt. Det hadde vært interessant å høre litt om hva som egentlig har endret seg, og hvordan en idiomatisk Angluar 2.0-applikasjon vil se ut.

**Comment by mikaelbr** [comment]
Enig! Det er noe jeg har alt for liten innsyn i selv og kunne gjerne tenkt meg mer informasjon om det. Har du noen tips til foredragsholder?

**Comment by bendiksolheim** [comment]
Glemte rent å svare her ser jeg. Jeg har dessverre null kunnskap om Angular 2.0 selv, og kjenner heller ikke noen som har det.

**Comment by oddsve** [comment]
Da vil jeg slå et slag for min nye kollega Kristian Tryggestad. Han hadde nettopp en internt foredrag om Angular 2. Han har jobbet med dette i prosjekt siden i fjorhøst.

**Comment by mikaelbr** [comment]
Veldig bra! Tar kontakt, @oddsve.

**Comment by bendiksolheim** [comment]
Closer issuen siden dette håndteres i #20 :)

**Comment by mikaelbr** [comment]
:+1:
