### ISSUE TITLE
Mars 2016: Angular

### ISSUE THREAD

**Issue by mikaelbr** [BartJS/meetups#20]
Plan for mars 2016 er @larrifax med en presentasjon om Angular 2. Har du noen flere detaljer du kan komme med, @larrifax?

Tentativ dato er 30. mars for meetup og 31. mars for podcast innspilling.

Innspill, @krakels eller @tmn?

Skulle vi ha invitert en til som engasjerer seg rundt Angular til podcasten?

**Comment by larrifax** [comment]
Siden Angular 2 ikke har vært på tapetet på BartJS tidligere, og siden de fleste ikke har satt seg inn i dette rammeverket enda, tenkte jeg å kjøre en presentasjon som introduserer Angular 2.

**Tittel:** Angular 2.0 - En introduksjon
**Abstract:**
> Angular 1 ble utgitt i 2009, og har siden den gang blitt det mest populære rammeverket for utvikling av rike nettsider og single-page applications (SPA). Etter fremtoget til React og de senere års utvikling på nettleserfronten, har Angular-teamet bestemt seg for å starte med blanke ark. Resultatet er Angular 2, et flunkende nytt rammeverk som støtter opp om nye og kommende web-standarder, og som ikke minst skal ta opp kampen med React og resten av røkla. I dette foredraget vil vi se nærmere på Angular 2.0 - som fremdeles er i beta-versjon - og utforske noe av dets funksjoner, API, og (litt) uvante syntaks. Underveis får vi også et innblikk i ulike konsepter den nye versjonen låner fra sin forgjenger og andre rammeverk som React.

**Bio:**
> Kristian Tryggestad jobber som konsulent hos Acando i Trondheim. Han anser seg selv som en full-stack utvikler, og er veldig glad i alt som har med web å gjøre (inkludert CSS!). Til daglig sitter han ute hos kunde der han jobber med det aller nyeste innen C#, TypeScript og Angular 2.

Jeg holdt dette foredraget internt i Acando for noen uker siden, og da tok det ~45 minutter med minimalt med tid til til spørsmål. Regner med at jeg trenger noe av det samme denne gangen også. Hvis ikke må jeg kutte deler av innholdet.

**Comment by mikaelbr** [comment]
Veldig bra, @larrifax. Jeg oppretter en Meetup på det i morgen.

**Comment by mikaelbr** [comment]
Meetup ligger her: http://www.meetup.com/BartJS/events/229279312/ Kan announce den (sende ut e-post) om den ser bra ut.

Planen blir da som følger:

* 30. mars: Meetup med presentasjon av Angular 2
* 31. mars: Podcast hvor vi snakker om Angular.

Det som mangler er en person til som f.eks har mye prosjekterfaring og investert i Angular til podcasten.

**Comment by larrifax** [comment]
Ser bra ut den :+1:

**Comment by mikaelbr** [comment]
Hei @larrifax ! Da er det straks klart for meetup. Er alt klart? Er det noen spørsmål før i morgen?

Jeg sendte ut en e-post med litt informasjon til alle deltakere nå:

> * Det blir servert mat (svinegryte) og drikke (brus og øl) sponset av Fundator.
> * Det starter 18:00 i kantina på Fundators kontorer (Strandveien 43).
> * Det er gratisparkering med god plass på grusplassen på baksiden av bygget dersom du skal kjøre.
> * Foredraget varer i ca 40 minutter og holdes av Kristian Tryggestad fra Acando.

I tillegg er det snakk om at det blir forsøkt å satt opp et PA/mic-oppsett ettersom det er så mange som kommer. Jeg har etterspurt informasjon om prosjektoroppsett. Er det noe spesielt du trenger for foredragets del?

**Comment by larrifax** [comment]
Heisann! Alt er klart til i morgen. Nå gjenstår det kun å se om formen holder seg sånn noenlunde, ettersom jeg har slitt med en forkjølelse helt siden før påske. Regner dog med at stemmen skal holde, så tror ikke det vil by på allverdens problemer.

Når det gjelder prosjektoroppsett så baserer presentasjonen seg i stor grad på kodeeksempler. Det hadde derfor vært flott om lerretet hadde vært såpass stort at publikum ikke trenger å ta med seg kikkert for å se.

PC'en jeg tar med har VGA og DP Mini porter. Jeg skal også prøve å huske på å ta med meg en DP Mini -> HDMI adapter. Da regner jeg med at jeg får koblet meg opp på prosjektøren de stiller med.

**Comment by mikaelbr** [comment]
Flott. Jeg avventer svar på hva slags oppsett det er så ser vi om det er noe kriseoppsett.

**Comment by mikaelbr** [comment]
Her er svar fra verter:
> HDMI funker ja, det er 4:3-format som ser best ut. 
> Vi har testet bilde og lyd i dag, ser ut til å bli bra! 

Det kan være verdt å sjekke ut hvordan presentasjonen din ser ut i 4:3-format, men 16:9 fungerer sikkert og på prosjektoren id needs be.

---

@larrifax En annen ting er Podcasten i morgen. Håper det fremdeles passer for din del og at stemmen/formen holder. Det er ikke veldig mye sermoni rundt det. Du kan møte opp hos BEKKs kontorer (Ferjemannsveien 10, bedre kjent som Adressabygget) og ringe meg når du står utenfor (telefon: 979 81 877). Vi snakker bare løst og ledig om Angular 2.0. Dersom du har et headset du kan bruke, ta gjerne med det. Eller så kan jeg prøve å låne et til deg. Ingen utstyr trengs utover det – med mindre du vil bruke en laptop for notater eller lignende. Det blir satt opp mikrofoner og alt av opptaksutstyr av @krakels her.

**Comment by larrifax** [comment]
Ok, skal få sjekket ut det med 4:3-format. Jeg satser på å møte opp litt før 6 i dag, slik at jeg kan få testet oppsettet. 

Når det gjelder Podcasten i morgen; når på døgnet skal jeg møte opp? Headset skal jeg greie å ta med selv, så lenge det ikke trenger å ha en god mikrofon. :)

**Comment by mikaelbr** [comment]
Glemte selvfølgelig å skrive det: Tror vi kan ta det rundt 20:00 dersom det passer for din del? Det er fordelaktig for din del om headsetet er lydisolerende (blir enklere å høre andre og seg selv).

**Comment by larrifax** [comment]
20:00 passer fint for meg det. Tar med et Bose-headset jeg, det skal vel holde. ;)

**Comment by mikaelbr** [comment]
Møt gjerne opp 17:30 i dag, så kan vi teste ut litt. Jeg har spurt etter et telefonnummer vi kan ringe når vi kommer frem. Jeg kan sende det på e-post (har du e-post jeg kan sende det til?), når jeg får det.

QC-headset funker topp og er det samme som vi bruker. :+1:

**Comment by larrifax** [comment]
Jeg la inn e-posten min på github-profilen, så nå skal det forhåpentligvis dukke opp der. Dukker opp rundt 17:30 jeg.

**Comment by mikaelbr** [comment]
Fikk beskjed nå om at 16:9 format så og bra ut. Utgjør vel ingen forskjell om det funker for din del, men da vet du det i alle fall.

**Comment by mikaelbr** [comment]
@larrifax Har du lenkene til ting som kan deles?

**Comment by larrifax** [comment]
Presentasjon: https://speakerdeck.com/larrifax/angular-2-en-introduksjon
Eksempler (disse ligger også på egen slide i presentasjonen):

1. Hello World - http://plnkr.co/edit/8z8ZinVi19UbEvSr77OW
2. View Syntax - http://plnkr.co/edit/VO40tsmJEaa0vWXPm00M
3. DI & Local vars - http://plnkr.co/edit/dawjk1EUacubwbPrJvz4
4. Child Components - http://plnkr.co/edit/IkfBUPdxESIdDeX8jeM7
5. Forms - http://plnkr.co/edit/scCWNoyaCq9zMvDBNOD7
6. Parent/Child (bonus) - http://plnkr.co/edit/DsZUzoQz6P2BY7skhhWu

**Comment by mikaelbr** [comment]
Denne er nå vell gjennomført! Bra jobba av både @larrifax og Fundator!
