### ISSUE TITLE
April 2016

### ISSUE THREAD

**Issue by mikaelbr** [BartJS/meetups#21]
Physical web/BLE er en mulighet for neste meetup.

**Comment by ketile** [comment]
Tanken er å kommunisere med Bluetooth-enheter via Web Bluetooth API som er under utvikling av Chrome, Opera og Firefox. Dette betyr at man kan både lese og skrive data til en Bluetooth-enhet fra nettleseren i en mobil/pad/laptop/stasjonær. 

Dette er en ny teknologi som jeg tror vil være meget spennende for web-utviklere. Tenkte å vise frem noen av demonstrasjonene vi i Nordic Semiconductor har laget og beskrive hvordan det hele henger sammen.

[Candy Grabber](https://www.youtube.com/watch?v=uwq1zP1_fAY)
[Candy Dispenser](https://www.youtube.com/watch?v=jcVhkGRs2FQ)

Bonus: Godteri.

**Comment by mikaelbr** [comment]
Veldig kult, og helt enig! Tror dette er absolutt noe som kommer til å være spennende og aktuelt fremover. Har testa ut litt selv og integrert mot et par BLE-enheter. Veldig gøy og høy demofaktor i tillegg.

Er det slik at dere i Nordic kan hoste meetup-en og, eller skal jeg finne et lokale vi kan ha det i?
Når passer det for deg?

Ville gjerne hatt deg med på BartJS Podcast i ettertid og. Vanligvis kjører vi det dagen etter meetup, men det er ikke fastsatt. Podcasten er veldig lavterskla og er bare til å møte opp og snakke.

**Comment by ketile** [comment]
Så bra! Fint om du kan finne lokale. Hvilke datoer og tidspunkter er aktuelle?

**Comment by mikaelbr** [comment]
Det som hadde passet best var Podcast innspilling 28.04 (typisk klokken 20:00 til 22:00 kanskje), og da kanskje meetup 27. ca 18:00.

**Comment by ketile** [comment]
Datoer og tidspunkt passer for oss. 

Dere må gjerne komme med innspill til innhold. Vi ser for oss noe slikt:

- Introdusere Nordic Semiconductor
- Kort om Bluetooth 4.0
- Ressurser
  - nRF Master Control Panel
  - GitHub repoer
- Physical Web
  - Eddystone URL
  - Web Bluetooth API
- Demonstrasjoner
  - Beacon
  - Solar Beacon
  - Candy Machine
  - Candy Dispenser
- Gjennomgang av kode
- Hacking
- Premiering

Det hadde vært gøy om vi kunne kombinere litt teori med praksis...

**Comment by mikaelbr** [comment]
Ser veldig bra ut! Hva legger du egentlig i "hacking"? Er dette tenkt som et kurs/hands-on Meetup?
Har dere noen spesielle krav til lokasjon for selve Meetup-en?

Om dere kan skrive et abstract (basert på outline ovenfor) og kanskje en lite kjapp introduksjon om dere så kan jeg opprette en meetup på Meetup.com for det alt nå.

**Comment by ketile** [comment]
Tanken bak _hacking _ er å ha en hands-on aktivitet. Dersom det høres interessant ut bør folk ha mulighet for å koble opp en laptop. 

Kommer tilbake til deg med mer dokumentasjon :)

**Comment by ketile** [comment]
Ønsker dere å ha Meetup'en på norsk eller engelsk?

**Comment by mikaelbr** [comment]
Det får være helt opp til dere og hva dere syns er enklest og hva dere er komfortabel med. Som regel er ikke presentasjoner på engelsk – men det har skjedd.

**Comment by mikaelbr** [comment]
Hvor mange blir dere og hvor mange personer kan dere ta? Dersom det er et hands-on aspekt av det. Dette virker som et opplegg som kan ta litt tid, så det er mulig vi burde få sponset noe mat og drikke. Er det noe problem for dere dersom vi får inn en sponsor som ikke er Nordic Semiconductor, eventuelt er dette noe Nordic ser for seg å kunne sponse? (Pizza + Brus for f.eks 30 stk er typisk rundt 3000)

**Comment by ketile** [comment]
OK. Da tar vi utgangspunkt i at presentasjonen blir på norsk. 

Antar at vi blir en eller to personer fra Nordic. I tillegg tar vi med en studentgruppe på fire som kan hjelpe til.

Skal sjekke muligheten for sponsing.

**Comment by ketile** [comment]
Nordic Semi kan dekke utgifter til Pizza og Brus for 30 personer. Gi beskjed når du vet hvor Meetup'en blir så fikser vi bestillingen.

**Comment by mikaelbr** [comment]
Veldig bra! Da skal jeg undersøke litt om lokaler der vi har tilgang på flere pulter og strøm som vi kan være på.

**Comment by mikaelbr** [comment]
For å være helt tydelig slik at det ikke blir noen misforståelser: Er det snakk om at Nordic Semi sponser mat/drikke for 30 + 2 ansatte + 4 studenter, eller 30 totalt? Dette er relevant for hvor mange jeg skal sette på som grensen til RSVP på Meetup og for hvilket lokale vi trenger.

**Comment by ketile** [comment]
Fint at du spør. Vi kan dekke for 30 deltagere + de som måtte være med fra vår side.

**Comment by mikaelbr** [comment]
Supert! Takk for svar.

Da er neste skritt:
1. Dere fullfører og sender meg et abstract som jeg kan legge ut på Meetup.com
2. Jeg finner et lokale som huser ~35 personer. Jeg tror Adressabygget har mulighet for det ved kantina så man kan spise mat og drikke brus.
3. Gjennomføre Meetup. Dere kan møte opp 45 minutter før og teste ut alt av utstyr om det er ønskelig.
4. Møte opp til Podcast. Podcasten blir på følgende format:
  - ~10 min JavaScript nytt (diskutere noe som har skjedd i det siste.). Ikke fastsatt tema enda, men skal få gjort det innen dagen. Håper gjerne dere blir med på diskusjonen og lufter tanker og idéer.
  - ~25 min diskusjon om Bluetooth API i Browser. Muligheter det gir, osv.
  - ~5 min avslutning/oppsummering osv.

Spørsmål om planen fremover, eller andre kommentarer?

**Comment by mikaelbr** [comment]
Hei igjen! Har dere noe konkret abstract på dette, så kan jeg få lagt det ut på Meetup.com?

**Comment by ketile** [comment]
ABSTRACT

**Physical Web**
Physical Web gjør det mulig å kommunisere med fysiske *ting* fra nettleseren via Bluetooth. Som webutvikler får du med litt JavaScript kontroll over hardware som tidligere var forbeholdt native applikasjoner. Med Physical Web kan du:

- [Fly Grumpy Cat](https://www.youtube.com/watch?v=tRMcMDIyIGQ)
- [Finne bortkomne dyr](https://www.youtube.com/watch?v=-Y77cUI_z30)
- [Betale parkeringsavgift](https://www.youtube.com/watch?v=ysxB_PXFImE)
- [Styre BB-8](https://www.youtube.com/watch?v=VwSLt0ipmAQ)
- [Styre godterimaskiner](https://www.youtube.com/watch?v=uwq1zP1_fAY)

Trondheimsbedriften Nordic Semiconductor er verdens ledende leverandør av innebygde kretser for Bluetooth Smart og samarbeider med Google, Opera og ARM i utviklingen av Physical Web. 

På Meetup'en får du:
- Lære om Bluetooth Smart
- Lære om Physical Web
- Se demonstrasjoner
- Eksperimentere

Nordic Semiconductor ser frem til en uformell, hyggelig og lærerik Meetup med BartJS.

> Physical Web er fremdeles under utvikling og for å få tilgang til mest mulig funksjonalitet bør du som deltager ha tilgang til en Android mobil med Marshmallow (6.0+).

**Comment by mikaelbr** [comment]
Det er lagt ut nå og jeg har promotert litt på diverse kanaler. Håper dere kan ta dere tid til å svare på spørsmål i kommentar-feltene, f.eks: http://www.meetup.com/BartJS/events/230470306/?comment_table_id=464163923&comment_table_name=event_comment

**Comment by mikaelbr** [comment]
Da er det klart til meetup! Jeg kommer til å stikke til lokalet og forberede det til klokken 17:00 i morgen. Skal sette fram pulter og strøm til 30 personer og gjøre klart til tilkobling.

Det vil som sagt tidligere være HDMI- og VGA-utgang og en 16:9 prosjektør.

Noen andre spørsmål før i morgen?

**Comment by ketile** [comment]
Supert! Vi kommer ca. klokken 16:00 og kan hjelpe til med rigging. Pizza leveres 16:45.

Har du noen formening om hvilke OS deltagerne har på laptop og mobil?

**Comment by mikaelbr** [comment]
> Har du noen formening om hvilke OS deltagerne har på laptop og mobil?

Dessverre. Det er nok en godt blandet gjeng. Men det er sikkert noen som har Android osv, så det må være mulig å sitte sammen f.eks.

**Comment by mikaelbr** [comment]
Vet du om det ble husket på glutenfri Pizza (http://www.meetup.com/BartJS/events/230470306/?comment_table_id=464445219&comment_table_name=event_comment)?

**Comment by ketile** [comment]
Glutenfri Pizza er bestilt!

**Comment by mikaelbr** [comment]
Veldig bra. Godt jobba!

**Comment by mikaelbr** [comment]
Takk for god innsats i går, @ketile! Det er i dag klart for Podcast og håper det fremdeles passer for din del. Dersom det er én til som vil bli med fra de som var der, kan hun/han fint joine. Vi satser på å starte innspillingen rundt 20:00, så møt opp samme sted som i går ca da. Ring meg (979 81 877) når du står utenfor så skal jeg åpne til deg.

Litt om podcasten: Det er en månedlig JavaScript podcast, hvor vi inviterer de som har snakka på meetupen til å diskutere noe rundt det de har presentert. Jeg tenker det kunne vært interessant å diskutere bare kjapt:
 - Hva kommer i nettleseren av API (hva slags muligheter får man og hva har man nå)
 - Kjapp intro til hvordan Bluetooth API-et er oppbygd, services, characteristics, uuid/discover osv.
 - Hva kan dette bety for Web? Hva slags muligheter får man av bluetooth og hva ser fremtiden ut som.

Den delen av podcasten vil vare ca 20 min.

Så kan du gjerne (og eventuelt en ekstra hjelper som du tar med deg) velge ut en lenke som dere ønsker å plugge. Det kan være relatert til dette temaet eller bare noe dere syns lytterne kan lære av.

**Comment by ketile** [comment]
Selv takk for god organisering av Meetup @mikaelbr ! 

Har ikke mulighet til å være med på innspilling av podcast men har sendt forespørselen videre til studentene. Dersom de har mulighet til å stille tar de kontakt med deg.

@hmhalvorsen @jtguggedal Kan dere gi Mikael et svar i løpet av dagen?

**Comment by mikaelbr** [comment]
Skulle gjerne hatt svar så raskt som mulig, for om ikke må jeg finne noen erstattere selv.

**Comment by jtguggedal** [comment]
Jeg har ikke mulighet i kveld. 

Takk for at vi fikk komme i går, det var veldig lærerikt og gøy å få være med!

**Comment by mikaelbr** [comment]
Er det et tidspunkt som passer bedre for dere eller er det generelt lav interesse for å delta på podcast? Det er selvsagt helt valgfritt, men det er en veldig lavterskla samtale uten noe krav til forberedelse eller noe å være nervøs over. Hør på andre episoder her: https://soundcloud.com/bartjs

**Comment by mikaelbr** [comment]
Vi har og mulighet til å gjøre mandag neste uke.

**Comment by ketile** [comment]
Mandag passer bra for min del. Er det mulig å gjennomføre innspillingen etter jobb? 5-6 tiden?

**Comment by mikaelbr** [comment]
Ja, det er etter jobb det blir gjort, vanligvis 20:00 for å rekke å sette opp litt utstyr, men vi kan klare 18:00 på mandag?

**Comment by hmhalvorsen** [comment]
Beklager for sen respons. Var veldig givende og gøy å være med i går, veldig artig å få en slik respons på arbeidet vi har gjort!

For min del er ønsket å putte alle ressurser på bacheloroppgaven, da innlevering er rett rundt hjørnet.

**Comment by ketile** [comment]
Supert. Da sier vi mandag kl 18:00.

**Comment by mikaelbr** [comment]
@ketile Flott. Da snakkes vi på mandag.

@hmhalvorsen og @jtguggedal Lykke til på bacheloren!

**Comment by mikaelbr** [comment]
Meetup og podcast vell gjennomført. 🍰

**Comment by ketile** [comment]
Takk for hyggelig podcast. Får håpe det ble sagt noe _vettugt_.

Dersom noen i BartJS føler trangen til å fortsette med Physical Web har jeg et par [nRF52 DK](https://www.nordicsemi.com/eng/Products/Bluetooth-Smart-Bluetooth-low-energy/nRF52-DK) å gi bort. nRF52 er forøvrig [verdens kraftigste Bluetooth Smart SoC](https://www.youtube.com/watch?v=ja3USlRVAok).

**Comment by mikaelbr** [comment]
@ketile Jeg tror det ble veldig mye vettugt!

> Dersom noen i BartJS føler trangen til å fortsette med Physical Web har jeg et par nRF52 DK å gi bort. nRF52 er forøvrig verdens kraftigste Bluetooth Smart SoC.

Så kult! Kanskje vi kunne tatt en god gammaldags "konkurranse" på BartJS' Facebook og Twitter-konto. Slike er visst populære og det blir mer rettferdig for hvem som får de. Hva tror du om det?

**Comment by ketile** [comment]
Konkurranse høres bra ut. Kjør på :+1:

**Comment by jtguggedal** [comment]
Jeg kom til å tenke på at det kanskje er noen som kunne tenke seg å teste Web Bluetooth APIet, men mangler BLE-enheter å koble seg opp til (og ikke vinner konkurransen). Da er denne appen fra teamet bak Web Bluetooth API et godt alternativ:
https://play.google.com/store/apps/details?id=io.github.webbluetoothcg.bletestperipheral

Med den appen, kan man både lese fra og skrive til karakteristikker, og man kan motta notifications fra en karakteristikk. Jeg har brukt den mye for enkelt å kunne teste toveis-kommunikasjon og sjekke at koden fungerer. De bruker standard UUIDer som 'heart_rate' og 'battery_service', som gjør at man slipper unna disse lange 128 bits-UUIDene man ofte ellers må bruke.

Ellers er nRF Master Control Panel for å scanne alle BLE-enheter i nærheten og se hvilke servicer og karakteristikker de annonserer veldig nyttig når man jobber med BLE:
https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp

Også denne som gjør at telefonen fungerer som en Eddystone-beacon er fin å ha for å teste Physical Web i praksis: 
https://play.google.com/store/apps/details?id=com.jrwc.amaapp.physicalwebbeacon

**Comment by hmhalvorsen** [comment]
For å føye på det @jtguggedal skrev:

Kan være nyttig å benytte denne appen for å sjekke hvilke Bluetooth-funksjoner mobilen din støtter:
https://play.google.com/store/apps/details?id=com.kyriakosalexandrou.bluetoothsupportcheck
Denne har spart meg for litt hodebry.

**Comment by mikaelbr** [comment]
@ketile Hvor mange enheter snakker vi om? Og kan det sendes ut, eller burde vinnere være fra Trondheim?

**Comment by mikaelbr** [comment]
[Podcast-episoden er lagt ut nå!](https://soundcloud.com/bartjs/episode-4-javascript-the-destroyer) så tenkte å legge ut konkurransen samtidig.

**Comment by ketile** [comment]
@mikaelbr Har lagt av tre kits til premiering. Vinnerne må ha mulighet til å hente kit i Trondheim.

**Comment by mikaelbr** [comment]
Flott! Da utlyser jeg konkurransen!
