### ISSUE TITLE
Mai 2016: Leaflet toolchain and rants

### ISSUE THREAD

**Issue by IvanSanchez** [BartJS/meetups#22]
Hi!

Brief introduction: I'm a Spaniard working for @MazeMap in Adressabygget (I guess I might have met @mikaelbr in the cantina queue?), doing a lot of @Leaflet stuff.

I can gladly talk about some tools I had to develop for Leaflet 1.0.0-rc1: Leafdoc and prosthetic-hand (the later has a [blog post](http://leafletjs.com/2016/03/20/debugging-touch-interactions.html)), plus some thoughts about JavaScript fatigue, incompatibilities in browsers, WebGL, ES2016 and general ranting.

I guess I can easily put together 30 minutes worth of slides & examples.

If this sounds like a good idea, we can schedule it for May.

**Comment by mikaelbr** [comment]
Hi @IvanSanchez,

Great stuff! Yeah, we probably have met in the cantina at some point 🍰 

This sounds like a very good idea and we're more than happy to schedule it for May. I would suggest you try to think about a focus for your talk and write an abstract for what you'd like your message to be, and we'll try to find a day and time in May that works for all parties?

We would also love it if you were interested in partaking in the BartJS Podcast after the meetup. The agenda would typically be something like:

- ~10 minutes of JavaScript news/general. Maybe for instance about "fatigue".
- ~25 minutes discussing some detail of your talk. If you are to talk about Leaflet, maybe some detail about that.
- ~5 minutes of wrap-up/summary/picks or what ever.

Let me know what you think.

**Comment by IvanSanchez** [comment]
Cool :smile: 

I think «LeafletJS hacks and toolchain» would be a good title.

The abstract could look like:

«How is it to develop a library used by thousands of developers? Iván will talk about how it is to fix bugs in LeafletJS, which tools are used, and how new browser features impact development.
A popular library like LeafletJS has peculiar requirements - some of the code pushes some browser features to their limits, and browser hacks and inconsistencies have to be treated with extra care.
How to select your tools is important in this day of so-called "JavaScript Fatigue", and when to develop new ones, even more so.»

I think that would cover most of the things I can talk about.

I'll be happy to take part in the podcast, but bear in mind that my norwegian still sucks, and trondesk gets me confused.

**Comment by mikaelbr** [comment]
Ah. I didn't even think about the language. I'll discuss with the producer/co-host for what vision we have for the podcast in regards with language in the podcast, and I'll get back to you.

**Comment by mikaelbr** [comment]
Should we pick up the thread here? What date is good for you?

**Comment by IvanSanchez** [comment]
Yeah. I don't have any big preferences, but I'll say wednesday 25th.

**Comment by mikaelbr** [comment]
If we're doing Wednesday 25th, we have to get things in motion and announce the meetup on Meetup.com.

Did you find anything out with regards to sponsoring food? Will you take charge of booking room and things like that?

**Comment by IvanSanchez** [comment]
I can take charge of booking the room in Adressabygget, and @MazeMap will sponsor some drinks and snacks (but I don't think we can afford pizza right now) :-)

**Comment by mikaelbr** [comment]
I see. There's absolutely no need to sponsor anything. We can have the meetup at 19:00 giving people the chance to eat before.

**Comment by IvanSanchez** [comment]
The room at Addressabygget is reserved, and @MazeMap will proceed forward with a secret plan involving beer and chocolate.

I agree that 19:00 sounds like a good time.

**Comment by mikaelbr** [comment]
I'll post it on Meetup.com and announce it! 👍

**Comment by mikaelbr** [comment]
If this looks good: http://www.meetup.com/BartJS/events/230563677/ I'll announce it now.

**Comment by IvanSanchez** [comment]
Looks good :-D

**Comment by mikaelbr** [comment]
Announced! I'll be there a bit earlier to help you set up and be of as much assistance as I can.

**Comment by IvanSanchez** [comment]
You mean you'll hold the doors open? :-P

**Comment by mikaelbr** [comment]
Hehe. Something like that. Hold the doors open, hook up the sound if you need a microphone, possibly print out BartJS Posters to guide people, etc. Depends on what you want help with 🎩

**Comment by IvanSanchez** [comment]
@mikaelbr I just got an email saying that somebody at Adressa double-booked the room, and I'm thrown out.

What shall we do?

**Comment by mikaelbr** [comment]
Wow. That's lousy. I guess I can check if our offices is free. It should be enough room there for the amount of people that's signed up.

**Comment by mikaelbr** [comment]
I've booked a "presentation zone" at BEKKs office in Adressabygget now, if we need it.

**Comment by mikaelbr** [comment]
By the way, I'm sorry to say there won't be an podcast episode for this Meetup - but we will be doing a WebRebels (the JavaScript conference in Oslo) Special this time around.

**Comment by IvanSanchez** [comment]
Yeah, using Bekk's offices will be the best option right now. Thanks for that!

**Comment by mikaelbr** [comment]
Then we'll do that. 👍 I'll probably have to shuttle people and do stairs workout in the beginning. I'll try to get someone else to help as well.

**Comment by mikaelbr** [comment]
@IvanSanchez Call or send me a message when I should come down ang get you: 97981877

**Comment by mikaelbr** [comment]
Thanks for sponsoring drinks and doing the presentation!

**Comment by IvanSanchez** [comment]
My pleasure. See you next time!
