### ISSUE TITLE
Juni 2016: Aurelia

### ISSUE THREAD

**Issue by mikaelbr** [BartJS/meetups#23]
@palktonderAtpowelno har ytret interesse rundt å snakke om Aurelia i juni.
Tentativ diskusjon.

**Comment by mikaelbr** [comment]
@palktonderAtpowelno Hvordan ser denne ut?

**Comment by palktonderAtpowelno** [comment]
Hvis vi kan ta det mot midten/slutten av måneden, så bør det gå bra

**Comment by mikaelbr** [comment]
Det høres bra ut for min del. Vi kan komme tilbake til spesifikt dato senere, men om jeg får en title og et abstract av deg så kan jeg legge ut informasjon på Meetup.com.

Jeg håper og du har mulighet til å delta på en podcast-episode. Dette er typisk 2 timer dagen etter Meetup-en. Veldig lav-terskla og man trenger ikke å forberede seg på noen måte.

**Comment by mikaelbr** [comment]
Liten oppfølging her, @palktonderAtpowelno. For om du har sett meldingen over.

**Comment by mikaelbr** [comment]
@palktonderAtpowelno Vært greit å fått spikra denne eller eventuelt få legge andre planer.

**Comment by palktonderAtpowelno** [comment]
Enig. Hva trenger du når det gjelder abstract (lengde/innhold)? (Skal myse mot Angular 2.0 meetup'en for å få litt inspirasjon der)

**Comment by mikaelbr** [comment]
@palktonderAtpowelno Kan sikte deg opp mot ikke lengre enn 40 minutter tror jeg. Føler det er en magisk grense på hvor lenge folk kan være interessert.

Dette er det vi skulle hatt:
1. Title/Abstract med beskrivelse på hva folk som går på presentasjonen kan forvente.
2. Vi setter en dato
3. Sted å være på. Det er mulig vi kan være i Adressabygget igjen om det fungerer bra.
4. En dag for eventuell podcast-innspilling. Typisk dagen etter dersom det passer for deg.

Ellers er det bare å møte opp den dagen meetupen er ca 30 min før for å koble opp og teste ut, så skal resten være fikset.

Noen spørsmål utover det?

**Comment by palktonderAtpowelno** [comment]
Den er grei. Jeg skal få på plass en abstract i løpet av morgendagen. Deretter trenger jeg ihvertfall en uke av ettermiddager på å få på plass presentasjonen. Når det gjelder det praktiske rundt så er jeg åpen for det meste

**Comment by mikaelbr** [comment]
Flott. Jeg kommer tilbake med et forslag til dato snart, så tar vi det derfra. Håper å få legge ut på Meetup.com innen et par dager, med komplett abstract, dato og plass.

**Comment by palktonderAtpowelno** [comment]
_Hva med dette som abstract?:_

Aurelia - Angular 2.0 light - On Speed v/Pål Kristian Tønder
De siste årene har vi sett en eksplosiv vekst av forskjellige Javascriptbiblioteker og rammeverk. I den sammenheng har det oppstått mange diskusjoner om hva som er den "optimale" måten å utvikle Javascript-baserte løsninger på. En av diskusjonene er knyttet til om enveis eller toveis binding er best, en annen om innføringen av class er en forbedring av Javascript eller det verste valget i IT-bransjen siden innføringen av null.

Aurelia er et nytt rammeverk for utvikling av rike nettsider og single-page applications (SPA) som støtter opp om nye og kommende web-standarder. Med utgangspunkt i toveisbinding og aktiv bruk av ES2016-konstruksjoner som klasser prøver rammeverket å støtte rask utvikling uten å bli påtrengende. Gjennom prinsippet om konvensjon over konfigurasjon prøver rammeverket aktivt å begrense koden man er nødt til å skrive. I dette foredraget vil vi se nærmere på Aurelia - som fremdeles er i beta-versjon - og utforske noe av de mulighetene rammeverket tilbyr og de erfaringene vi har med bruken av det.

Pål Kristian Tønder jobber med mobilitets- og skyløsninger i Powel Construction. Selv om han til daglig jobber på forretningssiden som produkteier og forretningsansarlig, følger han fremdeles den teknologiske utviklingen veldig tett og lurer seg til programmeringsoppgaver så fort muligheten byr seg. Han anser seg selv som en full-stack utvikler, og har fra en bakgrunn fra C++ og C# lært seg å bli glad i Javascript og HTML5.

**Comment by mikaelbr** [comment]
Ser bra ut! 👍 Jeg legger ut tentativ plan på Meetup.com

**Comment by mikaelbr** [comment]
Ligger ute her nå: http://www.meetup.com/BartJS/events/231719926/

**Comment by mikaelbr** [comment]
Hva med 23. juni?

**Comment by palktonderAtpowelno** [comment]
Høres greit ut

**Comment by mikaelbr** [comment]
Da ser meetup slik ut: http://www.meetup.com/BartJS/events/231719926/

Blir annonser så snart jeg booker rom.

**Comment by mikaelbr** [comment]
I dag er det Meetup! Håper alt er OK og du er klar for presentasjonen. Kom gjerne 18:30 i dag for å sette opp så vi er klar til 19:00. Det er HDMI- og VGA-inngang på prosjektoren og lyd om det trengs.

Ring meg på 97981877 for å slippe inn eller om det skulle være noe som helst.

**Comment by palktonderAtpowelno** [comment]
Jeg er så klar som jeg kommer til å bli :-). Er der rundt 18:30 så jeg får sjekket at alt fungerer som det skal.

**Comment by mikaelbr** [comment]
Flott! Da snakkes vi

**Comment by mikaelbr** [comment]
Takk igjen for et vell gjennomført foredrag, @palktonderAtpowelno ! 

Er det en dag som passer godt for deg med Podcast? Typisk kanskje kl 20:00 en kveld. Samme gjelder deg, @larrifax?

Og ikke minst @krakels

**Comment by Krakels** [comment]
For min del passer alle hverdager denne uka, bortsett fra fredag.

**Comment by larrifax** [comment]
Samme her. Er opptatt fredag, men har tid resten av uka.

**Comment by mikaelbr** [comment]
Flott! Da avventer vi svar fra @palktonderAtpowelno og eventuelt får vi ta det kanskje i morgen eller onsdag, så får vi gjort det så tidlig som mulig.

**Comment by palktonderAtpowelno** [comment]
Onsdag går bra for meg

**Comment by mikaelbr** [comment]
Fantastisk. Da sier vi onsdag klokken 20:00! Møt opp på BEKKs kontorer og ring meg når dere er der (979 81 877) så skal jeg komme å åpne. Trenger ikke mye forberedelse før innspillingen, men kan sikkert være greit for @palktonderAtpowelno å tenke litt over hvordan du vil gå frem for å forklare enkelt hva Aurelia er og @larrifax kan f.eks tenke ut noen spørsmål som han lurer på.

Dette blir bra! Bare send meg e-post eller skriv her om det skulle være noen spørsmål.

**Comment by mikaelbr** [comment]
Husk Podcast i dag klokken 20:00, @palktonderAtpowelno og @larrifax ! 👍

**Comment by palktonderAtpowelno** [comment]
Hei Mikael,

Her er lenken til demo-appen jeg brukte under foredraget: https://github.com/palktonderAtpowelno/aurelia-features

Jeg har også lagt ved PowerPoint'en jeg benyttet:
[Aurelia – Angular 2 light - On Speed.pptx](https://github.com/BartJS/meetups/files/344441/Aurelia.Angular.2.light.-.On.Speed.pptx)

Regner med at du kan gjøre dette tilgjengelig på en fornuftig måte. Nå tar jeg ferie :-)

**Comment by mikaelbr** [comment]
Hei! Takk for det. Jeg hadde store planer om å kontakte deg i går for å si fra at podcastepisoden er nå ute (se http://bartjs.io/episode-6-aurelia/), men gikk rett i glemmeboka.

Da har jeg lagt til den informasjonen i episode-detaljene! Og på https://soundcloud.com/bartjs

**Comment by mikaelbr** [comment]
Markerer denne som vell gjennomført!
