### ISSUE TITLE
Elm

### ISSUE THREAD

**Issue by mikaelbr** [BartJS/meetups#26]
From BartJS Slack: 

> Hey! I'm noah, I work at noredink. I wonder if there is any interest in an elm workshop/intro talk?

**Comment by mikaelbr** [comment]
This would absolutely be interesting. What would be required for us to make this happen? BartJS doesn't have any money/budget so it would be something we'd have to find sponsors for. But a workshop in Elm is very much something BartJS is interested in.

**Comment by eeue56** [comment]
Pretty much just give me a date, a room, and some people! An interactive workshop would be better over an intro talk, I think. The best way to learn is to make things

**Comment by mikaelbr** [comment]
I also think a workshop would be to prefer. We can do that. What time is better for you? In Norway we have a holiday season coming, so it might be that August is a good time. Or maybe early July

**Comment by eeue56** [comment]
August might be better for me, I think!

**Comment by mikaelbr** [comment]
Sounds good! I'll work on getting a good location. And we can get a more specific date later?

**Comment by eeue56** [comment]
Yep, sounds good!

**Comment by mikaelbr** [comment]
Hi, @eeue56 ! I've been in talk with a cool location here in Trondheim called [Work-Work](http://work-work.no/), and am about to find sponsors for a workshop room there. How long would you say a workshop is? Half a day (3-4 hours) or entire day (6-7)? Or something else? It would be nice to get some lay of the land to find a sponsor for paying for the workshop room and possibly food.

**Comment by mikaelbr** [comment]
@eeue56 Hi again! Do you have any more information for me, so we can get the ball running on this?

**Comment by eeue56** [comment]
@mikaelbr hi there! I will be busy on the 4th in Oslo, and busy between the 22nd-27th in Göteborg. 

The way I've done it before is about 30-60 mins of a talk where everyone can ask free questions while some basic examples and walking through how to get a program started, followed by 2 hours of coding with being around to answer any questions or help out with anythingthat's needed

**Comment by mikaelbr** [comment]
That sounds good to me. Do you have any preference in regards of day of the week? Could for instance Sunday the 14th work? Depending on how many interested there are. I was thinking a limit of maybe 30 people? Both due to location and also as there's only "one instructor".

**Comment by mikaelbr** [comment]
@eeue56 What do you think about Sunday 14th? Should I go a head and reserve location and create event?

**Comment by mikaelbr** [comment]
@eeue56 I'm still waiting for confirmation on this one. Obviously, the 14. can be short notice now, so we should maybe postpone this. I'm not able to assist any other date before late september, but maybe @eiriksm can help out?

**Comment by eeue56** [comment]
Hey! Sorry, I completely missed this. Yeah, the 14th probably isn't so good now - we should probably postpone this a bit

**Comment by mikaelbr** [comment]
I'd love to get a final date on this. What is the next available slot from your end of things?

**Comment by mikaelbr** [comment]
Hi, @eeue56. It's time to try to make this happen again. What do you think?

**Comment by trondkla** [comment]
I would love to see some Elm magic 😄

**Comment by mikaelbr** [comment]
This topic can now be closed. Would still welcome more presentations about Elm, though, so feel free to repoen.
