### ISSUE TITLE
Code in the Dark

### ISSUE THREAD

**Issue by mikaelbr** [BartJS/meetups#27]
Vi planlegger et `Code in the Dark` meetup. Hensikten er dels sosialt og for å ha det veldig moro. Code in the Dark er et lettbeint konkurranseformat hvor mange forutsetninger utnulles som gjør at mange kan delta.

Planen er som følger:
Vi arrangerer en event i f.eks baren til WorkWork hvor folk kan møte opp med laptop og delta i konkurransen. Man kan og bare møte opp for det sosiale uten å delta i konkurransen. Det er publikum og andre deltakere som bestemmer hvem som vinner. Etter selve konkurransen utnevnes det en vinner som vinner en premie. Resten av kvelden kan vi henge og være sosiale, sitte å hacke på noe, drikke noe godt (brus/kaffe/te/øl) eller bare spille noen brettspill.

## Regler for `Code in the Dark`

- Each contestant receives a bundle of the editor, which includes a screenshot of the page they should implement with HTML/CSS and any additional assets they might need.
- No iframes, frameworks, snippets or other assets outside of the ones listed in the instructions are allowed. The site should be built from scratch during the competition.
- The contestant should have the editor in full screen mode, and is never allowed to exit out of it or use any measurement tools.
- Previews of the results are strictly forbidden until the time is over.
- Once the 15 minute timer runs out each contestant presents their result to the audience, who then vote on their favorite to decide the winner.

## Hva trengs

- [ ] Reklamering/promotering. Skaffe så mange folk som mulig.
- [ ] **Premie**. En premie til den som vinner. Da trenger vi i såfall sponsor
- [ ] Et design som skal kopieres
- [x] ~~En dato~~. **Tirsdag, ~~12~~ 13. september**
- [x] **Lokale**. Helst en mer sosial plass med bar. ~~F.eks baren på Work-Work.~~. Det blir WorkWork
- [x] ~~Frivillige som kan se litt over og kontrollere at ingen jukser. (2 stk i tillegg til BartJS-folk?)~~ Publikum tar seg av dette.
- [x] Sette opp en nettside ala fork av http://codeinthedark.com/ (fra https://github.com/codeinthedark/codeinthedark.github.io)
- [x] Sette opp egen editor som en fork av https://github.com/codeinthedark/editor
- [x] Sette opp facebook event

Noe annet?

**Comment by eiriksm** [comment]
Så, for å være konstruktiv angående tid og sted: 

Hva med torsdag 9. september på Work-work (som allerede er et godt forslag)? Jeg kan ta kontakt med work-work :)

I reglene står det noe om "the audience". Skulle vi fått med noe om at man godt kan møte opp uten å være med?

**Comment by mikaelbr** [comment]
9. september er en torsdag? Og det er JavaZone fra 7-8, kanskje noen er med på det? Hva med uka etter? F.eks mandag 12. eller tirsdag 13.?

**Comment by eiriksm** [comment]
Heh, ja du har rett. Jeg mente vel 8. september. Og det er et godt poeng ang Javazone. 12. eller 13. blir bra. Så spørsmålet er vel: hva er best av mandag og tirsdag, mon tro.

**Comment by mikaelbr** [comment]
Jeg mistenker i grunn at tirsdag er bedre enn mandag. Men om det er representativt er jeg usikker på.

**Comment by mikaelbr** [comment]
Jeg tenker vi sier tirsdag 12. september. Folk får litt tid til å komme seg etter helga og det er en dag det skjer lite på Work-Work. Om f.eks WorkWork sier at det passer dårlig den dagen, kan vi høre om det er mulig å ha det mandag 11. september.

**Comment by mikaelbr** [comment]
Hva kunne vært en aktuell premie for noe som dette? Om vi skal skaffe sponsor burde vi kanskje komme med noe forslag til hva vi tenker. Si vi får 10-15 stk som melder seg på konkurransen (og flere som ser på), så kunne det jo vært greit å faktisk ha en skikkelig premie. F.eks rundt verdi ≥3000. En klassisk premie brukte å være iPad eller noe. Men det er kanskje litt over nå til dags? Andre forslag? "Delta på Podcast-episode" :P

**Comment by eiriksm** [comment]
Kontakter work work i dag, jeg.

Hadde vært kult med en såpass premie. Tror du noen vil sponse det, altså?

**Comment by mikaelbr** [comment]
Bra! 👍 
Tradisjonelt sett har det ikke vært så vanskelig å få sponsorer. Men det er mulig å undersøke i alle fall. Det vil jo da være ganske synlig reklame for de som sponser.

**Comment by eiriksm** [comment]
Apropos dato og ukedag. Tirsdag er 13. september, og ikke 12. Just sayin 😛

**Comment by mikaelbr** [comment]
Stemmer 👍  Fikk du sendt e-post til Work Work?

**Comment by eiriksm** [comment]
Det har jeg gjort!

**Comment by mikaelbr** [comment]
Vi har fått bekreftelse fra WorkWork. Ikke fått avtalt om vi får bruke prosjektør og lyd, men det tar vi etterhvert.

@eiriksm Vi burde få låst resten så kan vi reklamere for eventen. Spørsmålet er: trenger vi premie før vi annonserer eventen?

**Comment by eiriksm** [comment]
Jeg synes vi kan kjøre på med reklamering uten premie spikret

**Comment by mikaelbr** [comment]
Da sier vi det slik. Oppretter en meetup og starter promotering!

**Comment by mikaelbr** [comment]
Se mer informasjon her:
- https://www.meetup.com/BartJS/events/233440646/
- https://www.facebook.com/events/1655448911439416/
