### ISSUE TITLE
Maps and Mutants

### ISSUE THREAD

**Issue by IvanSanchez** [BartJS/meetups#28]
I've been playing around with DOM mutation observers lately, and maybe that might be an interesting topic for a BartJS presentation.

I'm thinking on something like:
- How web maps work
- Map tiles
- (Warning about map projections)
- Google Maps & "no reverse engineering"
- Using DOM mutation observers to not care about how it's done

Usual 30-minute presentation with slides and code and browsers and stuff.

My calendar is somewhat busy now, so maybe we want to schedule this for november or early december?

**Comment by mikaelbr** [comment]
Great! We'll have this in the backlog until you're ready. 🍰

**Comment by IvanSanchez** [comment]
OK, I think my calendar is clear enough now. I should be able to get some materials ready for the 1st or 2nd week of december.

**Comment by mikaelbr** [comment]
Great. I can book room and such at Adressa-bygget. Is there a particular date you prefer?

**Comment by IvanSanchez** [comment]
Dunno... December 8th? (that's a thursday)

**Comment by mikaelbr** [comment]
Sounds good to me. What do you think, @eiriksm ?

**Comment by eiriksm** [comment]
Great! Hm, wonder why I did not get an email for that mention

**Comment by mikaelbr** [comment]
@IvanSanchez Do you have an abstract for us?

**Comment by IvanSanchez** [comment]
I think something along the lines of:

«
There is a little-known feature in browser JavaScript, called "DOM Mutation Observers". They are not very useful for most use cases, but they open up possibilities for very interesting hacks.

In this meetup, Iván will make an introduction to how web maps work internally, and how mutation observers can enable developers to use web-based platforms that would be otherwise unavailable.
»

**Comment by mikaelbr** [comment]
I'll create a Meetup.com event on it 👍

**Comment by mikaelbr** [comment]
Here it is: https://www.meetup.com/BartJS/events/235941154/

Let me know what you think.

**Comment by mikaelbr** [comment]
I was so set on getting your feedback on this I forgot to announce the meetup. So now it's only 4 days until it's due. But probably it'll be OK. I'll announce it now and hope people come. If not, we'll postpone it. Sorry about that.

**Comment by mikaelbr** [comment]
No, I was mistaken. Apparently it was announced. Never mind

**Comment by mikaelbr** [comment]
@IvanSanchez Apparently, the meeting room at Adressabygget was taken. 👎 But the contingency is the BEKK Office as last time. I think that'll work just fine, or what do you think?

**Comment by IvanSanchez** [comment]
@mikaelbr I like the contingency plan. I'll make sure to bring my laptop and extra video cables this time.

**Comment by mikaelbr** [comment]
Great. 👍 The projector does HDMI, so that's the standard you need to support. Other than that I think we're good. I'll update the meetup and specify where it is. On Thursday I'll set out all the chairs, make coffee and have it ready.
