### ISSUE TITLE
Mars: Ionic 2

### ISSUE THREAD

**Issue by stiasta** [BartJS/meetups#30]
Jeg har prøvd meg på noen ionic 2 apper og kunne sikkert hatt en workshop på dette.
Foreløpig så har jeg litt lite tid til overs for å forberede en lengre workshop. Men jeg lufter værtfall ideen.

Hva kunne vært interessant å se i en slik workshop?  App fra A til Å med ionic cli og programmering?

**Comment by stiasta** [comment]
Jeg kunne også hatt workshop som handler om angular 2. Kanskje en form for intro.

**Comment by mikaelbr** [comment]
Høres veldig bra ut! Mange liker workshops og det er noe vi har hatt for lite av i BartJS-sammenheng generelt, men som vi ønsker å ha mer av.

Når det gjelder Angular 2 så kunne det sikkert ha blitt en veldig populær workshop. Forrige presentasjon vi hadde om Angular 2 (av @larrifax) møtte det opp over 60 personer (som er rekord i BartJS-sammenheng).

Ionic-utvikling er noe jeg har veldig lite erfaring med selv, men jeg ser for meg at det som kan være aktuelt er å få med litt av tradeoffs med å bruke teknologien av den typen? Vi har hatt om React Native før, hva er forskjellen med Ionic? Hva er den bedre på enn native utvikling? Det kan være aktuelle spørsmål å stille i en introduksjon til en workshop. Så burde kanskje målet være at de som møter opp vet hvordan de skal gå frem for å starte med et Ionic-prosjekt. Så om man har en eksempal app man kan implementere som ikke prøver å bite over for mye.

Det som ofte er vanskelig med workshops er å ikke lage en "paint by numbers"-tilnærming. Dersom man bare går fra punkt 1 til 2 til 3, så kan det være vanskelig å se helheten i det. Og jeg tror at dersom man bare satser på å lære seg magiske CLI-kommandoer for å gjøre "mest mulig på kortest mulig tid" så vil man kanskje sitte igjen med lite varig kunnskap. Kunne vært interessant å sitte igjen med litt mer av fundamentet til hva som ligger til grunn for Ionic-apps og hvilken filosofi den bygger på. Det tror jeg kanskje i alle fall kunne gitt høy verdi, men det hadde vært greit med andres tanker rundt det og (cc @eiriksm )

**Comment by stiasta** [comment]
Så bra at du syntes det hørtes interessant ut. 

Jeg kan selvfølgelig ha en liten slide i starten av workshoppen som forklarer forskjeller og hvorfor man burde velge det ene eller det andre verktøyet for å utvikle apps.

Usikker på om det er retoriske spm eller om du lurer på det, derfor kan jeg kort svare litt på det du lurer på.

> ...  det som kan være aktuelt er å få med litt av tradeoffs med å bruke teknologien av den typen? 
og
> Hva er den bedre på enn native utvikling? 

Hybridrammeverk begynner nå å bli så bra at det kan starte å kjennes som native apps når man bruker det på mobile enheter. Hvis man skal lage spill eller millisekundene teller så burde man programmere native. Men hvis man kan tillate marginalt mindre "snappy" apps så kan man bruke hybridrammeverk.

Det jeg synes er viktigst er hva er teamet som skal lage appen best på? Hvis man er rene C# utviklere så passer Xamarin. Hvis det er XAML så kan native script være svaret. Hvis man er web-utviklere så kan man bruke React Native, Ionic, eller noen av de andre rammeverkene som er der ute. Hvis man har programmert mest i React gå for React Native. Hvis man er kjent med Angular 1 eller 2 så kan man bruke ionic. Det handler bare om å kjenne til det som er der ute og hvilken muligheter man har.

Gode tilbakemeldinger om hvordan du kunne sett for det en workshop kunne gått fram. Jeg er enig i alt du sier om at det burde være en form for intro til ionic og det burde være en "guidet tour" for å få oversikt over det.

**Comment by mikaelbr** [comment]
Takk for svar! Jeg er enig i kommentarene dine. Jeg prøvde i utgangspunktet på å stille retoriske spørsmål for å fremprovosere litt tanker til hva man _kan_ fokusere på for en workshop, men jeg setter uansett pris på svarene! 👍

**Comment by eiriksm** [comment]
Synes også det høres ut som et interessant tema, og helt sikkert en del som er interessert i det. Og jeg tror også at det veldig mange lurer på er hybrid vs native, så jeg tror det er veldig lurt å ha med dette :p

**Comment by mikaelbr** [comment]
Har du tenkt noe mer på denne @stiasta? Vært kjekt om vi kunne låse noe innen de 3 første mnd av 2017.

**Comment by stiasta** [comment]
hei. Beklager kjempesent svar. har ikke fått noen varslinger fra github om comments :S 
Jeg har tenkt mer på det og jeg må se det an om jeg rekker å sette sammen et opplegg på en måned eller to. 

Tenker du at denne workshoppen burde bli arrangert i løpet av de første tre månedene?

**Comment by mikaelbr** [comment]
@stiasta Hei igjen! Denne hadde gått i glemmeboken min og.

Det kommer litt an på hva du får til. Det hadde passet bra å ta en workshop i mars for BartJS' del. Hva passer for deg?

**Comment by stiasta** [comment]
hei. Da har jeg kommet et stykke med oppsett av workshoppen. Tar gjerne i mot tilbakemeldinger.
[Her er linken]](https://1drv.ms/p/s!AhhUNxvJtUk-kgd3EvYwq5EpnwSa)

**Comment by mikaelbr** [comment]
Hva tenker vi om dato?

**Comment by stiasta** [comment]
jeg har lagt opp til midten - slutten av mars. 
hva tror du ?

**Comment by mikaelbr** [comment]
Kan fungere fint det. Hva med onsdag 22.?

**Comment by stiasta** [comment]
ja, det skal vel gå fint. Usikker på hvor lenge det skal vare da. skal jeg prøve å få det unna på en time? eller skal jeg bruke 2?

**Comment by mikaelbr** [comment]
Om det er en workshop, burde det nok være 2. Har du forslag til f.eks lokale? Og ofte med workshops så er det vanlig med f.eks mat. Har noe forslag til sponserer til f.eks pizza?

**Comment by stiasta** [comment]
mulig jeg kan få jobben til å sponse. skal sjekke.

**Comment by mikaelbr** [comment]
Ypperlig. Typisk kan man da begrense antall deltakere ut i fra budsjett og ambisjon osv. Med 1 person som holder workshop kan det bli vanskelig med mer enn 20 personer i utgangspunktet. Så da vil det kanskje være en kostnad på 2000-2500 kr (pizza + brus)

**Comment by stiasta** [comment]
Forslag til "demoprosjekt"

- todo app
- chat (integrasjon med en bartjs-kanal?) (mulig litt for vanskelig)
- [tour of heroes](https://angular.io/docs/ts/latest/tutorial/) (kortversjon)

**Comment by mikaelbr** [comment]
Husk at 1-2 timer er veldig kort tid å få noe gjort på. Ofte mye mindre enn man tror, selv om man er pessimistisk. Jeg ville anbefalt å scope ned problemet så godt det lar seg gjøre, men ha muligheter for "utvidelse" for de som er raske. Og ha alt som ikke er relevant for det man skal lære ferdiglaget. Om man skal lage en chat som integrerer opp mot en BartJS-kanal så kunne selve kommunikasjonen med Slack være ferdig laget og alt man trengte å gjøre var å bruke en funksjon.

**Comment by stiasta** [comment]
Sticos sponser mat 👍 
De lurer også på om det er mulighet for å sette opp en roll-up?

**Comment by mikaelbr** [comment]
Absolutt. Men da skal vi finne et lokale å ha det i. Det kan jo funke å bare ha det på Addressabygget. Tror det skal være tilgang på nett, strøm og bord her. Med mindre du har noen andre forslag?

**Comment by stiasta** [comment]
Det er kanskje det beste. Er jo i sentrum.

**Comment by stiasta** [comment]
@mikaelbr når bruker du å opprette meetup-eventen?

**Comment by stiasta** [comment]
jeg tenkte at oppgaven i workshoppen kunne være integrere med chatbotten vi har på jobb. Hva tror du om det?

**Comment by mikaelbr** [comment]
Chatbots er i vinden for tiden, så kan funke det. Jeg tenker det er lurt å ha abstract/title klart før jeg oppretter en event. Dette er informasjonen jeg har til nå:

Tid: Onsdag 22. mars, 17:00? 18:00? (Kan med fordel ha det 17:00 ettersom det er med mat)
Hvor: Adressabygget
Mat: Sticos sponser
Hva: Ionic 2 Workshop

Trenger tittel og abstract så er vi good to go. 👍

**Comment by stiasta** [comment]
Tenker du at vi bestiller mat eller er det noe du ordner?

**Comment by mikaelbr** [comment]
Som regel er det enklere at dere fikser det. Slik slipper man kompliserte økonomiske aspekter av det.

**Comment by stiasta** [comment]
her er det jeg har fram til nå. Kom gjerne med tilbakemeldinger for å spisse abstracten mer.
Tittel: Introduksjon til Ionic 2 - fra oppstart til deploy
Abstract: Lær deg hvordan man lager en hybrid-app ved å bruke Ionic 2 rammeverket. I denne workshoppen så vil dere bli guidet igjennom oppgaver som viser verktøy og framgangsmåte for når man skal lager en Ionic app fra bunnen av, til man har releaset til mobil.

**Comment by mikaelbr** [comment]
Da er event opprettet her: https://www.meetup.com/BartJS/events/238235146/

Se gjerne over og kom med feedback før jeg annonserer den (sender ut e-post til alle medlemmer).

**Comment by stiasta** [comment]
den ser bra ut 👍  
Er det pizza det vanligvis går i. Eller hender det seg at det er noe mer fancy? jeg tenker at pizza og koding vanligvis går litt hånd i hånd :D

**Comment by mikaelbr** [comment]
Kan gjerne være noe annet enn Pizza og. Det er bare praktisk og det kan bli levert. Men dette er helt opp til deg og sponsor.

**Comment by mikaelbr** [comment]
Da annonserer jeg den nå. Om alt er good.

**Comment by stiasta** [comment]
jeppsipeppsi

**Comment by mikaelbr** [comment]
Jeg tenker 20 stk er grensen på hva som er mulig for 1 person å assistere. Hva tror du?

**Comment by stiasta** [comment]
ja, tror det. Kan sikkert få noen kolleger til å hjelpe til hvis det er stort behov for det.

**Comment by mikaelbr** [comment]
Vi prøver med 20, så ser vi hvordan det går.

**Comment by stiasta** [comment]
den er grei

**Comment by stiasta** [comment]
blir spennende 👍

**Comment by mikaelbr** [comment]
Må utsette dette en halvtime for rommet vi skal være på er booket til 17:00. Håper det går bra. Så ny tid blir 17:30

**Comment by stiasta** [comment]
for min del går det bra.

**Comment by stiasta** [comment]
burde det spesifiseres at man skal ta med eget utstyr?

**Comment by mikaelbr** [comment]
Det kan vi gjøre

**Comment by mikaelbr** [comment]
Kan sende ut egen e-post til deltakere når det nærmer seg. Hva de burde ha på maskinen osv.

**Comment by stiasta** [comment]
bra. hvis deltakerene har lyst til å teste native funksjonalitet så må de ha med utstyr for å deploye til mobilen. iphone/mac/hackintosh med xcode, android med det som trengs for å deploye dit.

**Comment by stiasta** [comment]
Er det internett der ?

**Comment by mikaelbr** [comment]
Ja, det er et gjestenett som folk kan bruke. Men jeg ville sikret meg med å laste ned ting på forhånd om mulig.

**Comment by stiasta** [comment]
da ville jeg nesten ha sendt ut en oppskrift til installasjon av nodejs, vs code (eller lignende), og muligens npm pakkene som trengs. Skal jeg lage en liten oppskrift?

**Comment by stiasta** [comment]
en liten "must have" oppskrift for hardware og software

**Comment by mikaelbr** [comment]
Gjør gjerne det.

**Comment by stiasta** [comment]
okey. 
**Hardware**
- mac/hackintosh med iphone eller android. 
- PC med android.

**Software**
- Node JS
- Text editor: 
  - Visual studio code
  - Sublime
  - Vim 
  - eller lignende
- npm 
  - `npm install -g ionic cordova`

Skal jeg ta med oppsett av prosjekt og lokale installasjoner
i såfall så er oppskriften slik ->
- oppsett av ionic prosjekt
  - `ionic start chatbot --v2 --template blank
`
Jeg har også egen oppgave på dette i workshoppen

**Comment by stiasta** [comment]
så oppskriften grei ut @mikaelbr ?

**Comment by mikaelbr** [comment]
Ja, ser greit ut. Jeg skal sende ut en e-post når det nærmer seg.

**Comment by stiasta** [comment]
I samme epost, kan du høre om det er noen med matallergier?

**Comment by mikaelbr** [comment]
Det kan jeg! Sender ut e-post på mandag rundt lunsj-tider.

**Comment by stiasta** [comment]
høres bra ut.

**Comment by stiasta** [comment]
før du sender ut oppskriften så er det viktig å si at android studio 2.2 må lastes ned og ikke 2.3. Ikke oppdater noe etter installasjon. dette er pga kompatibilitet med ionic 2

**Comment by mikaelbr** [comment]
Men alt dette native-tingene er bare nødvendig dersom man ønsker å kompliere til spesifikke enheter? Er det en del av opplegget og tror du folk får tid til det?

**Comment by stiasta** [comment]
Ja det er egentlig bare nødvendig hvis man vil legge ut til sin mobil. Jeg har det som en del der jeg fort går igjennom hvordan man gjør det til ios. Det er ikke krise hvis de ikke får gjort det.

**Comment by mikaelbr** [comment]
OK. Da kan jeg spesifisere det. Jeg sender over teksten til e-posten her før jeg sender. Så kan du se om det er noe mer info du vil ha med.

**Comment by stiasta** [comment]
supert 👍

**Comment by mikaelbr** [comment]
E-post:

```
Hei!

På onsdag er det klart for workshop om Ionic 2 og du er påmeldt!

Har du ikke mulighet til å møte på onsdag likevel? Meld deg av så tidlig som mulig for å gi de som står på venteliste muligheten til å komme.

Det blir enkel mat til workshopen. Dersom du har noen allergier eller andre begrensninger for mat, svar på denne e-posten sporenstreks.

Her er en huskeliste for kurset:

- Ta med egen laptop.
- Software:
 - Node.JS
 - Din favoritt-editor.
 - Installert avhengigheter ionic og cordova via NPM: npm install -g ionic cordova

Om du vil sette opp prosjektet på forhånd kan det gjøres via:
   ionic start chatbot --v2 --template blank


Om du ønsker å få bygget prosjektet opp mot en enhet (f.eks iPhone eller Android), må du og sette opp egne verktøy for det:
 - Android:
   - Ha Android Studio 2.2 lastet ned og installert. Må være 2.2 da Ionic 2 ikke er kompatibelt med nyere.
 - iPhone:
   - Kan dessverre ikke laste over på iPhone uten å ha utviklerkonto, men kan ha XCode med Simulator installert.


Andre spørsmål? Ta kontakt her: https://github.com/BartJS/meetups/issues/30
```

**Comment by stiasta** [comment]
kunne ikke ha skrevet det bedre selv 👍 
Ser veldig bra ut.

**Comment by stiasta** [comment]
har det kommet inn noen allergier? jeg tenkte å bestille pizza og brus i morgen.

**Comment by mikaelbr** [comment]
Ingen allergier eller andre begrensninger. Fritt frem å bestille. Ingen som har meldt seg av heller, så det er foreløpig 6 stk på venteliste. Skal vi utvide, eller beholde det slik som det er?

**Comment by stiasta** [comment]
Jeg er litt usikker på hvor mange jeg kan hjelpe. Men det er en ganske rett fram workshop. Skal vi bare utvide da? Jeg vet om to fra jobben som kan angular 2 ganske bra. så de skal værtfall greie seg ganske bra. Jeg skal se om jeg kan få de til å hjelpe de som sitter sammen med dem.

**Comment by stiasta** [comment]
bare å utvide.

**Comment by mikaelbr** [comment]
Da utvider jeg det til 26 personer? 👍

**Comment by stiasta** [comment]
kjør på. De på jobben sa det var greit å plassere seg litt ut i rommet for å hjelpe til meg angular 2.

**Comment by stiasta** [comment]
han ene kan også litt ionic så jeg tror det skal gå fint.

**Comment by mikaelbr** [comment]
Perfekt 🎉

**Comment by stiasta** [comment]
Er det noe informasjon jeg må gi til peppes om hvordan de skal levere?

**Comment by mikaelbr** [comment]
Neida. Bare at det er Ferjemannsveien 10 (Adressabygget). Så kommer de utenfor og vi kan hente pizzaen der.

**Comment by stiasta** [comment]
pizza bestilt! 🍕

**Comment by stiasta** [comment]
har dere prosjektor med hdmikabel som går i pcen?

**Comment by mikaelbr** [comment]
Ja, det er både HDMI og VGA.

**Comment by stiasta** [comment]
konge! hva med thunderbolt ;)

**Comment by mikaelbr** [comment]
Dessverre, men kan stille med dongel til USB-C 🗄

**Comment by stiasta** [comment]
Det var veldig artig å være med på meetupen!
Vil du ha slides og kode inn i dette repoet?

**Comment by mikaelbr** [comment]
Takk for bidraget! Har vært alt for dårlig til å opprettholde alle slides osv, men tar mer enn gjerne i mot en PR med det her.

**Comment by stiasta** [comment]
den er grei 👍

**Comment by mikaelbr** [comment]
Vell gjennomført. 👍
