### ISSUE TITLE
ESLint 101

### ISSUE THREAD

**Issue by tbassetto** [BartJS/meetups#31]
Hei,

I have been working a lot with ESLint recently. I recently gave a talk at Framsia (front-end meetups in Oslo) about it and I think it went ok 😃. The talk goes from "why linting" to "why ESLint is the best" to "this is how you write a custom rule with the AST".

If it is of any interest to the BartJS community, I will just need advice on where to work remotely from Trondheim for 1 day.

**Comment by mikaelbr** [comment]
This sounds great. There are probably many interested in how to do "modern linting" and to hear the advatages of AST based linting instead of alternatives as jshint and what not.

We have a couple popular co-working spaces in Trondheim. Namely [Work-Work](http://work-work.no/) and [Digs](http://www.digs.no/). I don't know if they do one day renting, but it's worth a try I think. If not we'll try to find another place for you.

**Comment by mikaelbr** [comment]
@tbassetto What time horizon do you think here?

**Comment by tbassetto** [comment]
Any weekday starting from the 21th of November.

I am working on another slide deck about Physical Web and Web Bluetooth though. It may be more interesting, but it's not ready yet :)

**Comment by mikaelbr** [comment]
I think ESLint would be a good topic. We could definitely do Physical Web, but keep in mind we've had presentation from Nordic Semiconductor on that topic not too long ago, so that might reduce some interest in the turnout.

**Comment by tbassetto** [comment]
Fair enough. Are the slides from Nordic Semi available somewhere?

Early next week I am going to check with NSB which train ticket I can get. In theory I can get free tickets, but I haven't tried yet. If it turns out it doesn't include night trains to Trondheim, it may change my plan :/

**Comment by mikaelbr** [comment]
Keep us updated about when it is better for you and how the train tickets go.

Slides and resources from Ketil at Nordic can be found here: https://github.com/BartJS/meetups/tree/master/2016-April

**Comment by tbassetto** [comment]
It took me longer than expected because I was stuck home for the past few days. Anyway, I went to NSB today and it turns out that (surprise!) my profile is not complete in their system and I can't get my free tickets yet. It may take a while, I will comment again once it sorted out 😕

**Comment by mikaelbr** [comment]
Good. Do that and we'll figure a date out!

**Comment by mikaelbr** [comment]
Have you found out any more about this, @tbassetto ?

**Comment by tbassetto** [comment]
Not really sorry, I should have checked my status before suggesting a talk. I am waiting for a reply from NSB. It turns out that they do require more paperwork than expected so that I can get my "personalbillett".

**Comment by mikaelbr** [comment]
Let me know if anything changes, and we'll create an Meetup.com event on it

**Comment by tbassetto** [comment]
I 👏 got 👏 my 👏 NSB 👏 tickets.

Now we should find a date. BartJS seems to run on Tuesdays, 16th of February then?

**Comment by mikaelbr** [comment]
Great! There's no specific BartJS day. Could be any date for instance on week 7 (13. to 19. February), depending on works best for you.

**Comment by tbassetto** [comment]
The 16th looks better than the other days so far. I will post another comment as soon as I can get my tickets validated.

**Comment by mikaelbr** [comment]
Perfect. Let me know and I'll setup tentative meetup event. If you could think of an abstract that'll be great as well.

**Comment by tbassetto** [comment]
I have my tickets, I will be in Trondheim on the 16th of February.

* **Title:** ESLint from beginner to expert 
* **Abstract:**
> We'll learn:
> 1. What is ESLint and how does it compare to other linters.
> 2. How to configure it to get most of it.
> 3. How to create our own custom rules!

Does that work?

**Comment by mikaelbr** [comment]
Great! Thanks. I'll create an event on Meetup.com and announce it after the next one. I'll post the event here and you can review it.

**Comment by mikaelbr** [comment]
Tentative: https://www.meetup.com/BartJS/events/236822901/

**Comment by tbassetto** [comment]
Works for me. I forgot that I had a page on github.io haha :)

**Comment by tbassetto** [comment]
Hey Mikael, just wondering, have you announced the meetup?

**Comment by mikaelbr** [comment]
Hi! No, sorry. Haven't yet. Wanted to secure location etc before, but I guess it's fine. We can have it here, we're we've had it several times before.
