### ISSUE TITLE
Elm – Take 2

### ISSUE THREAD

**Issue by mikaelbr** [BartJS/meetups#33]
Vi prøver oss med Elm igjen. Denne gangen med @rechsteiner i førersetet og Eggs Design host.

Tentativt/forslag agenda:

- Foredrag om Elm
- Hacking

Hos Eggs, en gang i januar.

**Comment by mikaelbr** [comment]
@rechsteiner Det hadde vært ypperlig om vi kunne finne en dag som passer bra alt nå og legge ut en tentativ Meetup.com event. Hva tror du om f.eks 16. eller 17. januar?

**Comment by rechsteiner** [comment]
17. januar passer veldig bra!

**Comment by mikaelbr** [comment]
Flott. Jeg kan sette opp en Meetup på det. Har du tenkt på noe abstract/beskrivelse?

**Comment by rechsteiner** [comment]
Topp! Har ikke noen konkret beskrivelse akkurat nå, men kan skrive et lite forslag i morgen. Tenker hvertfall en ganske generell introduksjon kan være greit.

**Comment by mikaelbr** [comment]
Fikk du skrevet noe abstract på denne? Ikke noe hastverk sånn sett, men kjekt om vi kunne fått ut Meetup.com innen ei ukes tid så har vi den ute i en måned før arrangementet.

Trenger og informasjon om adresse, antall plasser og tidspunkt.

**Comment by rechsteiner** [comment]
Da fikk jeg endelig skrevet litt ✌️ Hva tror du om dette?

```
Elm er et funksjonelt programmeringsspråk som kompilerer til
Javascript. Det egner seg svært godt til å lage interaktive web
applikasjoner i en funksjonell og deklarativ stil. I tillegg åpner
Elms statiske typesystem for å skrive mer robuste applikasjoner, uten
en eneste runtime exception

I denne meetupen blir det en kjapp introduksjon av Elm og en
gjennomgang av hvordan man strukturer applikasjoner i The Elm
Architecture. Så bruker vi resten av kvelden på hacke sammen noe
kult. Målet i løpet av kvelden er å bygge Pong! Dette kommer til å
revolusjonere virtuell tennis-trening.

EGGS holder til i Kjøpmannsgata 40, rett over Bakgården. Ta med egen
laptop, så fikser vi mat og drikke.
```

Vi har sikkert plass til rundt 20-30 stk. Tenker det kan greit å starte rundt kl. 18, men er åpen for andre tidspunkt.

**Comment by mikaelbr** [comment]
Perfekt, @rechsteiner! Jeg lager event i morgen. Dette blir bra!

**Comment by mikaelbr** [comment]
Her er meetupen: https://www.meetup.com/BartJS/events/236110583/

Ikke announced enda. Tenker jeg blir å gjøre det i morgen til lunsj.

**Comment by mikaelbr** [comment]
@rechsteiner Skulle vi ha utvidet til 30 stk eller blir det for mye?

**Comment by mikaelbr** [comment]
Denne er vell gjennomført 👍
