### ISSUE TITLE
En kodekveld hvor folk lager bittesmå JavaScript-animasjoner på 140 tegn

### ISSUE THREAD

**Issue by iver56** [BartJS/meetups#34]
Hei :)
En kompis av meg har laget websiden [dwitter.net](https://dwitter.net), hvor man kan lage og dele små JavaScript-kodesnutter som tegner (imponerende) grafikk på et canvas-element.

Jeg ser for meg at vi kan møtes og lage demoer og vise de fram i løpet av kvelden. Kanskje man får til en premie for det beste bidraget? Det beste bidraget kan stemmes fram ved å bruke "Awesome"-knappen på dwitter.net

* Det er gøy
* Det er veldig lav terskel
* Det er en fin mulighet til å lære å tegne ting på canvas i javascript hvis man ikke har gjort det før
* Man lærer syke hacks for å korte ned på antall tegn (dette kalles kodegolfing)
* Man kan være kreativ og demonstrere matteskills

Jeg kan godt introdusere eventen med å vise fram noen tips og triks

**Comment by iver56** [comment]
Hva med torsdag 2. mars kl. 18? Vi kan være på Work-Work, enten i første etasje (puben) eller møterommet (andre etasje)

**Comment by iver56** [comment]
Hvis noen vil sponse mat/drikke er det veldig lov

**Comment by iver56** [comment]
Anbefalt begrensning på antall deltakere gitt at vi bruker møterommet på Work-Work: 25 personer

**Comment by mikaelbr** [comment]
Kult forslag! Forøvrig kan du se frem til over helgen der @krakels anbefaler dwitter på BartJS Podcast. Forøvrig har vi også en [egen episode på golfing](http://bartjs.io/episode-8-js-golfing/).

Syns dette høres ut som en kjempegod idé og kan absolutt gjennomføres i begynnelsen av mars. Dessverre er jeg borte den dagen, men det trenger ikke være til hinder.

**Comment by iver56** [comment]
Flott :) Da bare booker jeg det møterommet. @mikaelbr Lager du event på meetup.com?

Forslag til tekst:
Velkommen til en kodekveld hvor man skriver små kodesnutter som tegner grafikk på et canvas-element. Her slipper man å tenke på kodekvalitet, byggeverktøy og arkitektur. Denne kvelden er det nemlig kreativitet, matteskills og kodegolf (skrive kompakt kode) som gjelder. Ta med laptopen din. Terskelen for å komme i gang er lav, og det eneste du trenger av programvare er favorittnettleseren din, for vi kommer til å bruke nettstedet dwitter.net, hvor man skriver inn JavaScriptkoden sin og får se resultatet (grafikken) med en gang. Dette nettstedet er laget av tidligere NTNU-student Andreas Løve Selvik. Konseptet er at en kodesnutt på dette nettstedet skal være maks 140 tegn, for da den passer potensielt i en tweet. En slik kodesnutt som genererer grafikk kalles en dweet (demo tweet). Post gjerne mange dweets i løpet av kvelden. De vil bli vist fram på storskjerm. De beste dweetene blir kåret av deltakerne ved hjelp av upvotes på dwitter.net.

Iver Jordal setter i gang kodekvelden med å presentere noen tips og triks. Det blir lett servering.

Sted: Work-Work, møterom (opp trappa, 2. etasje)
Tid: Torsdag 2. mars kl. 18-20

**Comment by mikaelbr** [comment]
Bra saker! Jeg legger til nå. Som sagt vil jeg være vekke den dagen, men da overlater jeg alt ansvaret til deg for all gjennomføring 🎉

**Comment by mikaelbr** [comment]
Da ser det slik ut: https://www.meetup.com/BartJS/events/237983807/

Gi meg go når du vil jeg skal annonsere den. Det er mulig det blir litt kort varsel, men det passer sikkert for noen.

**Comment by iver56** [comment]
Go 👍

**Comment by mikaelbr** [comment]
Gone

**Comment by mikaelbr** [comment]
Da er denne gjennomført! Hvordan var det? Fungerte det bra?

**Comment by iver56** [comment]
Fikk tilbakemelding fra deltakerne at kodekvelden var gøy og at presentasjonen var bra. Det var dog relativt få som møtte opp i forhold til antall påmeldte. Noen nevnte at det kunne være på grunn av at det var javabin-meetup dagen før. Den visste jeg ikke om da jeg valgte dato. De mente at det ikke var for kort varsel på meetupen.

Her er de tre beste dweetene som ble laget i løpet av kodekvelden:

* https://www.dwitter.net/d/1788
* https://www.dwitter.net/d/1791
* https://www.dwitter.net/d/1783

I tillegg fant vi ut at man kan bruke Web Audio API til å generere sirenelyder på under 140 tegn:

https://www.dwitter.net/d/1792

**Comment by mikaelbr** [comment]
Bra oppsummering! Jeg forventet egentlig at det var for kort varsel. Vanligvis burde det være minst 14 dager før. Mange har familier som må organiseres osv.

**Comment by sigvef** [comment]
De som møtte opp synes nok ikke det var for kort varsel, men historien er kanskje annerledes for de som ikke dukket opp? Mulig selection bias i alle fall :)

**Comment by iver56** [comment]
Ja, jeg tenkte over akkurat det etter at jeg skrev det 😆 Godt poeng
