### ISSUE TITLE
LeafletJS-workshop

### ISSUE THREAD

**Issue by haugsand** [BartJS/meetups#35]
Jeg har nylig vært med på å holde en [LeafletJS](http://leafletjs.com/)-workshop for informatikk-studenter i Bergen, som potensielt kan videreutvikles og gjenbrukes for BartJS.

Workshopen forutsetter ikke mye Javascript-kompetanse, og passer nok best for de som har lite eller ingen erfaring med LeafletJS fra før av. 

I tillegg til å omtale sentrale klasser og metoder i LeafletJS, benyttes fetch til å hente åpne data fra Nasjonal vegdatabank. Vi berører også ChartJS, for å demonstrere at data kan visualiseres på ulike måter, samtidig. 

LeafletJS er enkelt, gøy og veldig visuelt!

**Comment by mikaelbr** [comment]
Høres bra ut @haugsand! Mange av de som kommer på BartJS Meetups er litt erfaren med JS, men jeg syns det er veldig positivt å ha for forskjellige spekter og erfaringsnivå. Og garantert mange som ikke har tatt i Leaflet før.

Vi har hatt noen tema rundt det tidligere, både via en av core contributors Iván Sánchez, og vi hadde en [intro-presentasjon av Emil Mork back in the day](https://www.meetup.com/BartJS/events/166089532/). Men jeg tror på ingen måte det er et uttappa tema.

Når tenker du et slikt opplegg kan holdes?

**Comment by mikaelbr** [comment]
Jeg har opprettet en initiell event som vi kan oppdatere etterhvert: https://www.meetup.com/BartJS/events/238235556/

**Comment by haugsand** [comment]
Jeg tenker at vi kan finne en passende dato i starten/midten av april. Meetupen kan holdes i Kantegas lokaler på Solsiden, og vi stiller med mat og drikke.

**Comment by mikaelbr** [comment]
Ypperlig 🎉 . Uke 15 er vel påsken? Så da uka etterpå f.eks. Kanskje rundt 19. april?

Utover det trenger jeg egentlig bare et abstract og tittel så kan jeg oppdatere eventen med informasjon så er vi good to go!

**Comment by haugsand** [comment]
Vi kan sette av 19. april til å gjennomføre workshopen, lokaler hos oss er reservert. 

Forslag til tittel: Visualisering av data på kart med LeafletJS. Jeg skal jobbe litt mer med et abstract.

**Comment by mikaelbr** [comment]
Sounds good 👍

**Comment by mikaelbr** [comment]
@haugsand Husk å tenk på abstract :) Ikke stress enda, men hadde vært supert å kunne annonsert meetupen rett etter neste (22. mars).

**Comment by mikaelbr** [comment]
@haugsand Fått sett noe mer på det?

**Comment by haugsand** [comment]
LeafletJS er et populært rammeverk for å lage kartløsninger, og benyttes blant annet av GitHub, Facebook og Pinterest. 

**Hvor:** Kantegabygget, Bassengbakken 4 
**Hva:** Workshop: Visualisering av data på kart med LeafletJS
**Når:** Onsdag, 19. april
**Mat:** Mat sponset av Kantega
**Holdt av:** Magnus Haugsand og Jørund Leknes

Ta med egen laptop, det eneste du trenger er nettleser, teksteditor og git. Samarbeid gjerne to og to.

**Abstract **
I denne workshopen vil dere få en innføring i å visualisere informasjon på kart i nettleseren, ved hjelp av Javascript-biblioteket Leaflet. Workshopen er bygd opp av en rekke praktiske oppgaver, der dere underveis må rette opp feil og mangler i en javascript-fil, for å få applikasjonen til å fungere som forventet. Workshopen forutsetter ikke mye Javascript-kompetanse, og passer nok best for de som har lite eller ingen erfaring med LeafletJS fra før av.

I tillegg til å omtale sentrale klasser og metoder i LeafletJS, benyttes fetch til å hente åpne data fra Nasjonal vegdatabank. Vi berører også ChartJS, for å demonstrere at data kan visualiseres på ulike måter, samtidig. LeafletJS er enkelt, gøy og veldig visuelt!

**Comment by mikaelbr** [comment]
Ypperlig. Legger ut nå og announcer til lunsj-tider.

**Comment by mikaelbr** [comment]
I morgen er det workshop! Det tror jeg blir bra. Foreløpig ser det ut som det er 36 påmeldt, men det ser ut som jeg dessverre ikke får tid til å møte opp, men det ser ut som dere har dette under kontroll. Typisk bruker det å være litt frafall, men om det kommer 30 stk tror jeg vi skal være veldig fornøyd.

Er det noe dere lurer på eller som jeg kan hjelpe med før i morgen?

**Comment by mikaelbr** [comment]
@haugsand Om det er noe dere trenger hjelp til under arrangeringen har jeg engasjert @krakels som med-hjelper.

**Comment by haugsand** [comment]
Utmerket! Jeg tror vi har alt under kontroll, kan ikke komme på noe vi trenger hjelp til akkurat nå.

**Comment by mikaelbr** [comment]
Denne er vell utført.

@haugsand Kunne du tenkt deg en uformell samtale på BartJS Podcast om noe av det dere hadde innlegg om? Jeg tenker litt snakk om kart i nettleser og leaflet spesifikt. En lavtersklet, uformell samtale som tar typisk maks 3 timer. Trenger ingen forberedelse. Interessert?

**Comment by mikaelbr** [comment]
@haugsand Sett denne og eventuelt tenkt på det?

**Comment by haugsand** [comment]
@mikaelbr Jeg la dessverre ikke merke til forespørselen før nå. Jeg kan bli med på en Podcast, gjerne ta kontakt via Slack.
