### ISSUE TITLE
Mai: Firebase som backend til komplekse SPAs (tidligere tittel: Forslag til talk)

### ISSUE THREAD

**Issue by christianalfoni** [BartJS/meetups#38]
Hepp,

Var på podcast og snakket om Cerebral (www.cerebraljs.com). Tenkte det kunne være interresant å høre om Ducky (startup jeg jobber hos) og hvordan vår arkitektur med SPA, Firebase, Firebase queues osv. henger sammen. Snakke om utfordringer rundt det å være en startup, bygge fort, mye endringer osv. Og da vise hva Cerebral faktisk tilbyr i en relativt stor kompleks applikasjon.

**Comment by mikaelbr** [comment]
Høres bra ut, @christianalfoni ! Når tenker du dette kan være aktuelt? Neste meetup er 19. april, så om du har mulighet til mai hadde det vært 👌 💯 .

**Comment by christianalfoni** [comment]
Jaaaa, det må jeg klare å få til :) Når i mai er det?

**Comment by mikaelbr** [comment]
Det er litt opp til når det passer best for deg.

**Comment by christianalfoni** [comment]
Y0! Beklager sent svar her, hva med siste uka i Mai?

**Comment by mikaelbr** [comment]
Hallo! Tenker du på uke 21 eller 22?

**Comment by christianalfoni** [comment]
22 :-)

**Comment by mikaelbr** [comment]
@christianalfoni Det kan funke. Mulig jeg ikke kan være med, da jeg reiser ned på WebRebels den uken. Men det lar seg vel løse. Er det en spesifikk dag som passer for deg?

**Comment by mikaelbr** [comment]
@christianalfoni Har du abstract og title? Så skal jeg lage en tentativ event på meetup.com

**Comment by christianalfoni** [comment]
Hepp igjen!

Onsdagen er kanskje god? Altså 31. Mai? Torsdag of fredag blir vrient for meg.

Btw, er det på norsk eller engelsk?

### Ducky, utvikle komplekse tjenester som startup

"Å være en startup med store ambisjoner krever andre teknologi-valg enn hvis man er en etablert bedrift eller et konsulent-selskap. Stadige endringer i konsept og mangel på ressurser skaper store utfordringer, men store utfordringer legger ofte til grunn nye innovasjoner og ideer. Bli med på en reise gjennom vår stack, både konsepter og konkret kode"

**Comment by mikaelbr** [comment]
Jeg tar nattog ned den dagen, så må som sagt finne noen som kan hoste det med sted osv, men det finnes sikkert en plass. Vet du om noe lokale som kan brukes?

Engelsk eller norsk er opp til deg og hva du er komfortabel med. Vi har noen engelsktalende som sikkert setter pris på engelsk, men absolutt ikke noe must. Om du føler presentasjonen blir enklere/bedre på norsk, vil jeg sagt det er mye viktigere.

**Comment by mikaelbr** [comment]
Foreløpig utkast her: https://www.meetup.com/BartJS/events/239634657/
(Ikke announced, men med dato og tid)

**Comment by christianalfoni** [comment]
Vi kunne jo hatt det på Ducky, hvor mange pleier å dukke opp ca.?

**Comment by mikaelbr** [comment]
Typisk 30, men det er opp til lokalet osv.

**Comment by christianalfoni** [comment]
Hm, ja, jeg kan ta en sjekk i morgen hvor mange vi har plass til. 30 tror jeg blir i overkant. Men kan eventuelt ta uka etter, null stress for min del. Er bare at vi har release nå på onsdag så må ha hodet på riktig sted de to neste ukene ;-)

**Comment by christianalfoni** [comment]
Okay, det er plass til 15 stk her... blir det veldig få?

**Comment by andrerav** [comment]
Hei! Fundator kan stille med lokaler, mat og drikke til denne meetupen. Vi kjører gjerne litt "high key"-opplegg slik som sist :)

**Comment by mikaelbr** [comment]
Flott! Jeg er som sagt borte den dagen, så kan dessverre ikke bidra, men dette har vel dere 💯 kontroll på. Jeg kan sette til lokalet på eventen og legge deg til som host, @andrerav, så løser dere dette?

Er det noe begrensning eller spesielle innstillinger jeg skal sette på? Er det noe dere trenger av meg utover det?

**Comment by andrerav** [comment]
Hvis du setter en begrensning på 70 påmeldte i første omgang så er det fint (blir det flere så må jeg først forsikre meg om at jeg får tak i nok manpower til rigging). Ellers er det tut og kjør for vår del :)

**Comment by mikaelbr** [comment]
70 tror jeg blir mer enn nok. Har endret noen detaljer her: https://www.meetup.com/BartJS/events/239634657/

Si gjerne om jeg skal endre på noe så kan jeg annonsere den i starten av neste uke.

**Comment by mikaelbr** [comment]
@christianalfoni Tenkte på det, kanskje det kan være lurt å nevne noen konkrete eksempler på hva man skal gå igjennom i presentasjonen? For å "selge det litt mer" og gjøre det mer håndfast.

**Comment by christianalfoni** [comment]
Y0!

Jepp, jobber med presentasjonen nå. Det blir litt jatting rundt utfordringer som startup og hvordan det påvirker teknologi-valg. Så blir det en reise fra spec, til komponenter, til klient, til database og service. Kommer til å vise mye kode og demoe innsikten man får ved hjelp av Cerebral på tvers av klient og server :-)

Btw, hvor mye tid har jeg?

Gi beskjed hvis du heller vil ha noe mer konkret i stikkord-format!

**Comment by mikaelbr** [comment]
Du har så lang tid som du ønsker å bruke. Typisk 30-40 minutter er det jeg mener passer bra. Jeg kunne egentlig gjerne ha tenkt meg noen konkrete ankerpunkt med kanskje noen spesifikke teknologier som du kan nevne. Det er litt lettere "salgbart" for å få folk til å dra

**Comment by christianalfoni** [comment]
Cool! :-)

Tenkte å hive meg rundt å ta det på engelsk forresten:

- Exploring the stack of a startup
- Same functional programming approach on client and server
- Handling side effects with functional programming
- Client and server merged debugging
- Firebase, Cerebral, Function-Tree, React, Node

**Comment by mikaelbr** [comment]
Bra! Jeg oppdaterer eventen og annonserer i morgen.

@andrerav Noe mer info du vil jeg skal ta med?

**Comment by mikaelbr** [comment]
@christianalfoni Oppdatert her: https://www.meetup.com/BartJS/events/239634657/

**Comment by andrerav** [comment]
Tittelen på meetupen er på norsk nå mens resten av meetup-beskrivelsen er på engelsk. Hva med å endre tittelen til noe sånt som "Ducky: Exploring the stack of a startup"?

**Comment by christianalfoni** [comment]
Perfect :-)

**Comment by mikaelbr** [comment]
Bra saker. Da announcer jeg.

**Comment by mikaelbr** [comment]
@christianalfoni @andrerav : I morgen er det klart for meetup. Er det noe dere vil jeg skal sende ut info om?

Jeg kan dessverre ikke delta, som sagt, så er det noen av dere som kunne videreformidlet en beskjed? Si gjerne at Trondheim Developer Conference burde ha flere frontend/javascript bidrag og at CFP stenger 1. juni. Alle må sende inn forslag den kvelden på https://submitit.trondheimdc.no/

**Comment by andrerav** [comment]
@mikaelbr Du kan kanskje sende ut en påminnelse om at det er hyggelig om eventuelle påmeldte som ikke har mulighet til å komme oppdaterer RSVP'en sin. 

@christianalfoni Jeg tar en kort intro med info om fasiliteter (toalett, nødutgang, mat/drikke, etc) og en kort outro til slutt med info om TrondheimDC og BartJS. Høres det greit ut?

**Comment by mikaelbr** [comment]
@andrerav Will do!

**Comment by andrerav** [comment]
@christianalfoni Vi stiller med prosjektør med HDMI og VGA, tar du med eventuelle nødvendige overganger hvis du har Mac e.l?

**Comment by christianalfoni** [comment]
@andrerav Det er gull! Har Mac med HDMI :-)

**Comment by christianalfoni** [comment]
@andrerav Btw, har du et telefonnummer jeg kan nå deg på? Jeg har en tendens til å ikke finne fram :-D

**Comment by andrerav** [comment]
@christianalfoni Her er en kartlink https://goo.gl/maps/izsD3ds7Zr92 Telefonnummeret mitt er 91700891 :) Jeg henger opp noen store gule plakater på inngangsdøren.

**Comment by mikaelbr** [comment]
Takk til @andrerav for bra arrangering og @christianalfoni for bidrag! 🎉 Dere er rå
