### ISSUE TITLE
Intro til typesystemet til ReasonML

### ISSUE THREAD

**Issue by mikaelbr** [BartJS/meetups#39]
Jeg har noe opplegg for intro til Flow-typesystemet. Om det kan være interessant å gå igjennom.

**Comment by AndersNS** [comment]
Ja, takk. Det hadde vært meganice.

**Comment by torgeir** [comment]
Ditto!

**Comment by mikaelbr** [comment]
Vi kan sette opp denne til juni f.eks

**Comment by mikaelbr** [comment]
For en horribel planlegging! Jeg endrer denne til ReasonML, og tar det i april

**Comment by mikaelbr** [comment]
Done and done.
