### ISSUE TITLE
Chatbot talk

### ISSUE THREAD

**Issue by budde377** [BartJS/meetups#40]
Jeg skal holde en presentation til JavaZone i september om hvordan vi brugte Node til at udvikle et bot-rammeværk. Jeg holder gerne en talk om det inden JavaZone, hvis det har interesse?

Her er mit abstract:

>More than a billion people are actively using Instant Messaging, making this a distribution channel with massive potential for delivering highly personalized content. Even today, you can book flights, buy a new pair of pants, or receive relevant news through IM; all this made possible with chatbots and the availability of Natural Language Proccessing services, such as Wit.ai, Api.ai, and Watson. Initiating contact to a chatbot through IM is now as easy as starting a conversation - in fact it is just that. Users do not need to install any app and they can reach you on the platforms they prefer.
>
>At Mito.ai we are developing the next investment platform using Facebook messenger as our sole distribution channel. This talk will cover how we designed, developed, redesigned, and redeveloped the Mito.ai chatbot. In particular, the talk will get into some of the problems we faced adapting to a new design paradigm, for example choosing and integrating a service for handling NLP, designing and keeping track of conversations, while making it all scale.
>
>Through examples we will propose a pattern for designing scalable chatbots independently of messaging platform and NLP service, enabling the audience to build chatbots of their own.

Buzzwords: *Node*, *Flow*, *Wit.ai*, *Facebook Messenger*

**Comment by mikaelbr** [comment]
Beklager sent svar her! Ferie har gjort meg lat og bedagelig tror jeg.

Vi kan gjerne ha en meetup på dette! Når tenker du det passer bra?

**Comment by mikaelbr** [comment]
Har lagt til en event på det her: https://www.meetup.com/BartJS/events/242348990/

Har du og noen tanker om hvor det kan holdes?

**Comment by budde377** [comment]
Jeg tænker slutningen af august vil passe mig godt, uge 34 eller 35. Eventuelt d. 31 August?
Jeg kan se om vi kan skaffe nogle lokaler hos Mito, ellers har i måske erfaring med at få plas på WorkWork eller DIGS?

**Comment by mikaelbr** [comment]
Jeg kan sjekke om mulighet til å holde det på Digs. Det koster vanligvis litt, men mulig vi har en avtale på det. 31. august passer ikke for meg i alle fall, men det trenger ikke være en hindring. Jeg foreslår egentlig i uke 34. F.eks 23. august.

**Comment by budde377** [comment]
D. 23 passer mig fint og vi betaler gerne udgifterne til venue.

**Comment by mikaelbr** [comment]
Da har jeg satt opp datoen her: https://www.meetup.com/BartJS/events/242348990/

Si fra om det er noe jeg skal endre.

Om dere har lyst til å ta ansvar for gjennomføringen/organiseringen av meetupen så hadde det vært prima 💯 det altså.

**Comment by budde377** [comment]
Det gør vi gerne. Skal vi da tage kontakt til DIGS? Og er der noget udover at sikre plads, som vi skal have på styr på inden?

**Comment by mikaelbr** [comment]
Supert! 👍 Da kan dere gjerne ta kontakt med Digs og, ja. Det er ikke så mye mer som skal til enn:

1. Fikse en plass å være.
2. Legg til alle detaljer på Meetup.com (sted, tid, og eventuell info om mat).
3. Sørg for at RSVP-innstillinger på Meetup.com-event matcher med antallet som er plass til på venue.
4. Bestill mat om det skal være noe mat (valgfritt)
5. Sørge for at venue har koblet til prosjektor og har alt det tekniske som man trenger.

Så møter folk opp til tiden som er spesifisert på Meetup.com og da er det bare til å ta i mot folket og sørge for at alle kommer seg inn.

**Comment by mikaelbr** [comment]
Sjekk og ut dette om du vil: https://github.com/BartJS/organisering/blob/master/organizing-meetup.md

**Comment by budde377** [comment]
Super!

**Comment by budde377** [comment]
Vi bliver nok nød til at rykke det til d. 31 alligevel, da der er TP i uge 34

**Comment by mikaelbr** [comment]
Den er grei! Så du endra selv. Bra! Jeg antar at du har rettigheter til å annonsere eventen selv og, når sted er funnet? Burde i utgangspunktet annonsere det minst 14 dager i forveien.

**Comment by budde377** [comment]
Ja, jeg har rettigheder på Meetup. Jeg regner med at få styr på sted idag
eller imorgen, så annoncerer jeg det der. Er der andre steder i plejer at
annoncere det?

**Comment by mikaelbr** [comment]
Kan trykke på "Announce" på toppen av eventen. Så skal jeg tweete og slik når det blir gjort 😄

**Comment by mikaelbr** [comment]
Funnet ut noe av lokale?

**Comment by budde377** [comment]
Vi har akkurat fundet lokale idag hos Kantega, så nu er vi klar til at lave reklame

**Comment by mikaelbr** [comment]
Kult, kult, kult. Så Marvin meldte seg på.

Er all informasjon som trengs der da?

**Comment by budde377** [comment]
You tell me ;) Men ja det tror jeg

**Comment by mikaelbr** [comment]
Nå er det satt til maks 30 stk, stemmer det?

**Comment by budde377** [comment]
Godt spørgsmål. Jeg checker lige

**Comment by budde377** [comment]
Vi kører med 35. Jeg går ud fra man kan ændre det senere

**Comment by mikaelbr** [comment]
God plan 👍  Jeg fikser, annonserer og tweeter/facebooker. 🍰

**Comment by mikaelbr** [comment]
@budde377 Det er meetup om 2 dager og det ser ut til å bli fullt hus! Det blir bra.

Jeg hører @computerlove har en ypperlig plan om mat til dagen og. Så jeg kan oppdatere eventen og sende ut generell infomail.

@computerlove Er det noe spesielt rundt lokalet jeg og burde skrive?

**Comment by computerlove** [comment]
Når de er utenfor kan de ringe 41160221 for å bli sluppet inn

**Comment by mikaelbr** [comment]
Flott. Da sender jeg ut e-post i lunsjen

**Comment by mikaelbr** [comment]
Oppdatert på https://www.meetup.com/BartJS/events/242348990/ og sendt ut epost

**Comment by budde377** [comment]
Ser frem til i aften. Super fedt at TDC vil sponsorere mat. @computerlove sig fra om jeg skal foretage mig noget ift. forplejning.

**Comment by computerlove** [comment]
Alt er i orden. Har bestilt 13 store pizza + brus fra Peppes, levering 18:45

**Comment by mikaelbr** [comment]
Prima greier @computerlove 🥇
