### ISSUE TITLE
GraphQL

### ISSUE THREAD

**Issue by exoer** [BartJS/meetups#41]
Jeg kan holde en presentasjon om GraphQL og mine erfaringer fra bygging av en crowd-funding site. 
- Om GraphQL
- apollo
- Graphiql
- resolvers/dataloaders
- integrasjon med react

Ser for meg å kunne holde den litt ut i oktober.

**Comment by mikaelbr** [comment]
Flott! Når du har et abstract og en formening om når i oktober du ønsker å gjøre det så kan vi opprette en event på det på Meetup.com

**Comment by mikaelbr** [comment]
@exoer Har du tenkt noe mer på denne?

**Comment by mikaelbr** [comment]
Ping, @exoer

**Comment by exoer** [comment]
Hei.

Har lyst til å presentere GraphQL.

Travelt, men slik er det altid, så egentlig er det bare å sette en dato.

Slutten av januar tidlig februar er realistisk å få den klar.

**Comment by mikaelbr** [comment]
Hei! Supert! 🌮 Vi kan si starten av mars da, f.eks?

**Comment by mikaelbr** [comment]
@exoer Hva tenker du om starten av mars?

**Comment by exoer** [comment]
Det bør gå bra. Har ca 45 slides klar nå :)

**Comment by mikaelbr** [comment]
@exoer kult! Gleder meg. Jeg var usikker på om dette ble noe av med det samme så jeg skaffet en alternativ i Mars. Hva tenker du, 2 meetups i Mars eller kunne du tenkt deg feks å ha det på samme meetup (15 mars) eller feks starten av april?

**Comment by exoer** [comment]
Kan hende jeg kan ha det klart til midten av februar. Skal ta en økt i
helga.

**Comment by mikaelbr** [comment]
Veldig bra. Blir litt samme som mars, kan ha 2 presentasjoner i meetupen https://www.meetup.com/BartJS/events/247343118/

**Comment by mikaelbr** [comment]
@exoer Om du skriver et abstract og en tittel, så kan jeg få det ut på eventen?

Hadde du forøvrig vært interessert i å ta en samtale i podcast-form for BartJS Podcast om GraphQL?

**Comment by mikaelbr** [comment]
@exoer Tror vi må få annonsert meetupen 19. februar (https://www.meetup.com/BartJS/events/247343118/) snart. Vet du noe mer her?

**Comment by exoer** [comment]
GraphQL is a new API standard that provides a more efficient, powerful and
flexible alternative to REST. It was developed and open-sourced by Facebook
and is now maintained by a large community of companies and individuals
from all over the world.

Arne Jenssen will give an introduction to GraphQL and tell about his
experience in using it in production on a crowdfundingsite.

----

Mulig å ta det 19 februar, men passer bedre i mars, så hvis det er mulig
foretrekker jeg det.

**Comment by mikaelbr** [comment]
> Mulig å ta det 19 februar, men passer bedre i mars, så hvis det er mulig foretrekker jeg det.

Da setter vi den opp i mars heller. 👌 Takk for abstract! Jeg legger det til eventen, så tar jeg kontakt igjen når det nærmer seg.

**Comment by mikaelbr** [comment]
Lagt til på https://www.meetup.com/BartJS/events/247343583/. Blir annonsert etter neste meetup. Si gjerne fra om det skal gjøres noen endringer.

**Comment by mikaelbr** [comment]
@exoer Kunne du tenkt deg å vært med på en podcast-episode til utgivelse denne mnd? Hvor vi snakker høyt og lavt om GraphQL. Det er ikke noe krav til forberedelse eller utstyr.

**Comment by mikaelbr** [comment]
Hei, @exoer ! På torsdag er det klart for meetup. Du starter presentasjonene fra 17:30 (etter mat). Du kan gjerne møte opp litt før 17:00 om du har mulighet til det, for å sjekke tilkobling av prosjektor og slike ting.

Det er tilkobling for HDMI, USB-C og DisplayPort. Trenger du en annen overgang?

Er det noe annet du lurer på før torsdag?

**Comment by exoer** [comment]
Gull

Jeg har mini-displayport på min gamle macbook pro. Har også overgang til
DVI.


satser på å komme litt før 17 da :)

2018-03-12 10:49 GMT+01:00 Mikael Brevik <notifications@github.com>:

**Comment by mikaelbr** [comment]
Gjennomført 👍

**Comment by mikaelbr** [comment]
@exoer Kunne du tenkt deg å gjennomføre en podcastepisode om GraphQL også? Veldig uformelt, bare snakker litt om det samme som du snakket om i presentasjonen din. Trenger ikke noe utstyr, vi stiller med alt.

**Comment by exoer** [comment]
Hei

Er ikke helt komfortabel med det dessverre

2018-04-04 14:28 GMT+02:00 Mikael Brevik <notifications@github.com>:

**Comment by mikaelbr** [comment]
Den er god! Takk for svar.
