### ISSUE TITLE
Declarative state and side effects

### ISSUE THREAD

**Issue by christianalfoni** [BartJS/meetups#44]
"Writing declarative code for our UIs is so common that we do not even think about it. But when it comes to writing logic for managing state and side effects it requires a lot of discipline to get the same benefits. We are going to talk about how we can get help writing our business logic in a declarative manner and see what benefits it gives us."

**Comment by mikaelbr** [comment]
👌 Nice, nice.

En spesifikk dag det passer i slutten av februar?

**Comment by christianalfoni** [comment]
Mmmm, en mandag eller tirsdag :)

**Comment by mikaelbr** [comment]
19. februar?

**Comment by christianalfoni** [comment]
Cool!

**Comment by mikaelbr** [comment]
Da setter jeg opp det 🎉

**Comment by mikaelbr** [comment]
https://www.meetup.com/BartJS/events/247343118/

**Comment by mikaelbr** [comment]
Vel gjennomført 👌
