### ISSUE TITLE
Musikkvisualisering med regl

### ISSUE THREAD

**Issue by mollerse** [BartJS/meetups#45]
WebGL gir deg muligheten til å drive med 3D-programmering i nettleseren og åpner for en del kule ting som før har vært forbeholdt desktop og native applikasjoner. Men WebGL og 3D-programmering kan være litt tungt å komme i gang med og involverer mange avanserte konsepter.

For å gjøre det til et morsomt prosjekt kombinerte jeg kreativ programmering, musikk, og et lite WebGL-rammeverk som heter regl, for å lære meg mer om 3D-programmering og WebGL.

Hvis dere har lyst, så kommer jeg gjerne en tur og prater litt om erfaringene fra det hobbyprosjektet. Det blir litt grunnleggende intro til WebGL og bibloteket [regl](http://regl.party), hvordan du kan visualisere musikk/lyd, og litt filosofering om hvordan du kan lære deg nye ting med kreativ programmering.

**Comment by mikaelbr** [comment]
16. mars?

**Comment by mollerse** [comment]
16. mars er en fin dag 👍

**Comment by mikaelbr** [comment]
Lagt ut: https://www.meetup.com/BartJS/events/247343583/

**Comment by mikaelbr** [comment]
Gjennomført 👍
