### ISSUE TITLE
THREE.js Workshop

### ISSUE THREAD

**Issue by mikaelbr** [BartJS/meetups#47]
# THREE.js Workshop

Opplegg finnes på http://iver.io/threejs/. Holdt av Iver Jordal og Håkon Hesselberg

## Forslag til tid

I november en gang.

## Behov for gjennomføring

- Workshop-rom
- Mat/Brus?

**Comment by iver56** [comment]
Da dette kurset ble holdt på Work-Work i slutten av september, var det Hackheim (Nikolai) som tok på seg hovedansvaret. Håkon var ikke med da.

Jeg kan godt være med og hjelpe folk under arrangementet, men jeg vil helst ikke ha hovedansvaret for presentering og gjennomføring. Jeg har egentlig nok med å arrangere meetups for Trondheim Machine Learning Meetup for tida ^^

**Comment by mikaelbr** [comment]
Tok litt tid før jeg kom tilbake til deg her! 😱 @iver56 Har du forslag til hvem som kan holde i den da? Organisering og logistikken av meetup er noe jeg kan fikse. Men skulle hatt noen til å presentere og holde i det faglige.

**Comment by iver56** [comment]
Flotta at du kan ta deg av organisering og logistikk! Nå for tida har jeg tid til å holde en slik presentasjon. Men ikke forvent at jeg er ekspert på feltet da :)

**Comment by mikaelbr** [comment]
Veldig bra, @iver56! Trenger ikke være en ekspert på feltet sånn jeg ser det. Tror mange vil ha glede av å gå igjennom http://iver.io/threejs/ og få en fin intro til hva dette handler om.

Er det et tidspunkt du ser for deg at dette kunne vært aktuelt?

**Comment by iver56** [comment]
Hva med 14. mars?

**Comment by mikaelbr** [comment]
Høres bra ut! Har du tilfeldigvis forslag til noen vi kan spørre om sponsor av pizza/brus?

**Comment by iver56** [comment]
Arm var sponsor da workshopen ble holdt sist

**Comment by mikaelbr** [comment]
Jeg har booka rom på Digs Workshop rom 14. mars! Kunne du har prøvd deg på et abstract så kan jeg opprette en event på meetup.com ?

**Comment by iver56** [comment]
Velkommen til en hands-on workshop med fokus på three.js. I løpet av to timer vil du lage en animert 3D-scene. Til slutt er det mulighet for å vise fram det du har laget. Ta med egen laptop og godt humør. Det er lav terskel, og du trenger ikke å installere noe, for all koding kommer til å skje i nettleseren på iver.io/threejs

[sett inn info om mat/snacks/drikke]

**Comment by mikaelbr** [comment]
Prima. Jeg oppretter en event i dag, så kan du se over før jeg annonserer?
Har du noe formening om hvor vi burde sette begrensning på antall deltagere?

**Comment by iver56** [comment]
Digs sitt workshoprom har begrenset kapasitet. La oss sette begrensning på 30 påmeldte, og så kommer det kanskje rundt 22-25.

**Comment by mikaelbr** [comment]
Høres bra ut. Jeg mistenker kapasitetbegrensningen er fasilitatorer/hjelpere mer enn rommet.

**Comment by mikaelbr** [comment]
@iver56 Her er eventen: https://www.meetup.com/BartJS/events/259335335/
Den er ikke announced enda, men om du sier go announcer jeg den i morgen til lunsj ca.

**Comment by iver56** [comment]
LGTM 👍 Go

**Comment by mikaelbr** [comment]
Announced

**Comment by mikaelbr** [comment]
I morgen er det meetup! 🥇  Er det noe spesielt du trenger eller preferanser på f.eks bordstilling? Det er tilkobling til HDMI der.

**Comment by mikaelbr** [comment]
Det er til nå registrert 29 personer. Veldig bra. Kommer det sannsynligvis noe rundt 20-25.

**Comment by iver56** [comment]
Tommel opp for HDMI! Når det gjelder bordstilling, har jeg ingen spesielle preferanser. Både klasserom-stil og hestesko-stil burde fungere bra. Wi-Fi er også kjekt å ha, siden man skal browse litt rundt på internett under workshopen :)

**Comment by mikaelbr** [comment]
Ja. Det skal jo være nett der, men vi får se hvor bra det fungerer. I verste fall fyrer jeg opp hotspot.

**Comment by iver56** [comment]
Jeg har forresten invitert en person (fra Hackheim) som kan være med og hjelpe folk, eller i det minste være rubber duck 🦆

**Comment by mikaelbr** [comment]
Supert!

**Comment by iver56** [comment]
Tenkte på en ting: Strømpadder. Ordner digs med strøm, slik at folk kan holde liv i laptopene sine?

**Comment by mikaelbr** [comment]
Er strøm der 👍

**Comment by mikaelbr** [comment]
Vellykket gjennomført 👍
